### ISSUE TITLE
Python typing 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1056]
**Return types, io to/from Python**
#627 addresses return types from Python to sheet, this issue addresses types as they are ingested from sheet to Python 

**current behavior:** everything is just ingested as an object from sheet to Python, additionally single column ranges are ingested as dataframe when they should just be a series 

**outline:** 
c(x,y) where the value of c(x,y) is an int should be int when brought into python 
c(x,y) where the value of c(x,y) is a float should be float when brought into python 

cells((x,y),(x,y)) where the range is one column should be brought in as a series in Python 
cells((x,y),(x,y)) where the range is multiple columns should be brought in as a dataframe in Python 
additionally
if a column in the range is all ints, the series type should be int64
if a column in the range has any floats alongside ints or exclusively floats, the series type should be float64
if a column in the range has any strings, the series type should be object 
if a column in the range is all bools, then the series type should be bool 
if a column in the range is all datetimes, then the series type should be datetime 
(take note of the distinctions above when mixing types, straightforward when all same, but also needs to take note of best approach when mixing)

![image](https://github.com/quadratichq/quadratic/assets/146771258/3ea2d018-249e-4ff5-9491-af85d31e8de2)
![image](https://github.com/quadratichq/quadratic/assets/146771258/173ba6f4-b9a6-4c3a-bf90-805cf50ba11e)

Type mapping 
https://app.quadratichq.com/file/1ad99fbb-f42b-44ee-b261-588c82136e2e

**Comment by davidkircos** [comment]
done
