### ISSUE TITLE
fix cell preview stickiness

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1060]
When you hover over a cell and get a preview, then you two finger pan on the trackpad, it tries to stay visible on the screen and follows you around which feels really awkward and glitchy. I would expect that, as soon as I start to pan around, the preview disappears. (The same thing happens when you start to pinch to zoom, and I would expect again that it disappears once I start zooming)

Video showing these cases:

https://github.com/quadratichq/quadratic/assets/1316441/8ed3ee35-d7c4-4461-b866-4c2cd1bfc590

**Comment by luke-quadratic** [comment]
fixes merged #1065
