### ISSUE TITLE
bug: text bleeds when going over vertical axis

### ISSUE THREAD

**Issue by N-Demir** [quadratichq/quadratic#1061]
Small amount of text in cell (0,0) that you would want to be readable:
<img width="212" alt="PNG image" src="https://github.com/quadratichq/quadratic/assets/23620644/8ddfe524-2043-400c-a509-e2ae9b9f9ae1">

Add long text to (-1, 0):
<img width="219" alt="PNG image" src="https://github.com/quadratichq/quadratic/assets/23620644/fecd5e3a-b5ad-4dd2-a6c1-9adb38334183">

End result:
<img width="210" alt="PNG image" src="https://github.com/quadratichq/quadratic/assets/23620644/cbf6988b-f0d5-44c1-9847-fca01654ef81">

**Comment by davidfig** [comment]
This is a real bug, and can be reproduced by editing the cell in (-1, y) when there's content in (0, y). On refresh, the clipping will again be correct. 

__Technical notes__: 

This is not specific to the x = -1/0 location, but instead relates to the text hash boxes. On an update to a cell within the text hash, the clipping is only checked for cells within that text hash. Neighboring hashes are (mistakenly) not checked. Here, the cell in (-1, 0) is in the (-1, 0) hash, and the cell in (0, 0) is in the (0, 0) hash.

During initial rendering (eg, after a refresh), hashes are checked against neighboring hashes, which results in proper clipping.

A PR is in the works to fix that neighboring hashes will be checked if there is overflow either into that hash or from that hash.
