### ISSUE TITLE
bug: "Cursor: (0, 0)" stops updating when on another sheet

### ISSUE THREAD

**Issue by N-Demir** [quadratichq/quadratic#1062]
So it seems like the "Cursor: (0, 0)" tracks the position of the cursor on the first sheet, but once you have multiple sheets in a file and you navigate to the second sheet that cursor tracking stops working and stays fixed to whatever cell you had selected in the first sheet. 

<img width="246" alt="Screenshot 2024-01-31 at 6 51 42 PM" src="https://github.com/quadratichq/quadratic/assets/23620644/5d5d0109-87f5-4c03-89ed-08c7013f6e32">

**Comment by davidfig** [comment]
Great catch. I didn't notice that before.

**Comment by luke-quadratic** [comment]
Resolved in #1048
