### ISSUE TITLE
Can't render cjk using bitmapText

### ISSUE THREAD

**Issue by ChasLui** [quadratichq/quadratic#107]
Can't render cjk using bitmapText

**Comment by davidkircos** [comment]
Could you provide more detail about what you are trying to accomplish?

**Comment by ChasLui** [comment]
For example, if you enter any Chinese '你好世界' in the cell, it cannot be rendered.

**Comment by davidkircos** [comment]
Ah yes, thank you for creating this issue. Quadratic fonts currently only
support ASCII.

**Comment by jimniels** [comment]
Closing, as this is a duplicate of #506
