### ISSUE TITLE
Grid is performant displaying and importing 50k cells

### ISSUE THREAD

**Issue by davidfig** [quadratichq/quadratic#1073]

**Comment by luke-quadratic** [comment]
@davidfig can you describe this a bit more? otherwise we should prob close because a bit too general

**Comment by davidfig** [comment]
Just a placeholder for my work related to performance. We want the grid to easily import and load sheets with 50k rows.

**Comment by luke-quadratic** [comment]
Cool, for reference there's a lot of perf stuff in #963 as well 👍

**Comment by luke-quadratic** [comment]
Web workers and other perf, reopen if big performance things become relevant after SQL etc
