### ISSUE TITLE
Spelling mistake in example sheet

### ISSUE THREAD

**Issue by th4lmain** [quadratichq/quadratic#1079]
Red box highlight. Should be 'built', not build. Very minor, but is a bad first impression.

![Screenshot 2024-02-03 at 18 18 51](https://github.com/quadratichq/quadratic/assets/77910773/eefd8e46-cc00-40d3-be87-80f42aea8e98)

**Comment by luke-quadratic** [comment]
thanks for the find @th4lmain, we'll get the fix in asap!
