### ISSUE TITLE
Onboarding & education improvements in-app 

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1093]
**[Revisit this issue after Teams/Workspaces restructuring]**

**Onboarding walkthrough**
Onboarding walkthrough when first opening the app, collect some information so we can help users better (e.g. education users get education focused features); see design in Figma for onboarding flow 

**Key actions tutorials**
Give users a key actions popup when they first do something 
- First time opening Python - pop-up explaining references, returning to sheet, etc.

**Comment by luke-quadratic** [comment]
Should we have additional prompts based on first time actions? Things that people are unlikely to understand immediately. 

An example: once someone creates their first new sheet (as in creates a second sheet in an existing file) we may want to teach them how to reference cells across sheets?

**Comment by luke-quadratic** [comment]
duplicate #1436
