### ISSUE TITLE
Can't stop execution with bad code 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1107]
'Stop execution' works for situations where things are functioning properly, not for the situations where you just want to abort. 

E.g. if you're in a long loop and want to stop execution it'll work, if you're stuck because something is broken you can't get out. (Give a shout if you need an example to brick the sheet with) 

[https://app.quadratichq.com/file/daccc77d-abf4-4c96-9c2b-7659940b0c52](https://app.quadratichq.com/file/daccc77d-abf4-4c96-9c2b-7659940b0c52)

![Image](https://github.com/quadratichq/quadratic/assets/146771258/de78ff82-4043-4b3c-b81b-22fff34afcee)

**Comment by luke-quadratic** [comment]
Was archived but just recreated on example sheet in original post

**Comment by ddimaria** [comment]
@luke-quadratic I can't access the example file in the description.  Can you paste the code used to brick this?
