### ISSUE TITLE
`requests` not working, `HTTPException("Failed to execute 'send' on 'XMLHttpRequest'`

### ISSUE THREAD

**Issue by N-Demir** [quadratichq/quadratic#1109]
Tried to use the requests library to fetch some data, and noticed it was failing. Simple reproducible example below:
```
import requests

url = 'http://www.google.com'
response = requests.get(url)

# If you want to print the response
print(response.text)
```

What I see:
![Screenshot 2024-02-20 at 12 01 47 PM](https://github.com/quadratichq/quadratic/assets/23620644/d4c85784-5108-4b85-80a7-f11264e22de6)

Using Brave Browser

Example taken from the docs:
https://docs.quadratichq.com/writing-python/ingest-data

Quadratic version:
3742f71

**Comment by N-Demir** [comment]
On safari I just get a: `ERROR: ConnectionError on line 4: ('Connection aborted.', HTTPException(' A network error occurred.'))`

**Comment by davidkircos** [comment]
This is a CORS error 
![CleanShot%202024-02-20%20at%2014 31 55@2x](https://github.com/quadratichq/quadratic/assets/3479421/c4bc815e-6111-4274-8425-cd1e5951fd65)

The solution is to use a CORS proxy. Quadratic is working on providing one

**Comment by N-Demir** [comment]
Workaround that David shared for now is to copy the code from: https://app.quadratichq.com/files/create?example=mercury_bank.grid
