### ISSUE TITLE
error `'await' outside async function` for functions with `cell` in them

### ISSUE THREAD

**Issue by N-Demir** [quadratichq/quadratic#1114]
I'm sure you're aware of this but I couldn't find an issue referencing it (though #1057 would fix this?)

```
def a():
    return cell(0, 0)

a()
```
fails with error `ERROR: SyntaxError on line 2: 'await' outside async function` assuming because `cell` is async

**Current Fix**
```
async def a():
    return cell(0, 0)

await a()
```
This might be unintuitive for folks not well versed in python and is annoying

**Reproducible Example**
https://app.quadratichq.com/file/19b4314e-d828-4bfb-9b8f-4784c1320acd

**Comment by luke-quadratic** [comment]
Should work now in prod @N-Demir 🎊
