### ISSUE TITLE
Data Validation: dropdown cell value selector, checkbox, date-picker, etc.

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1140]
Validation whose option(s) can be read by other cells, code, etc. 

Validation to-do's (in order of user requests/priority): 

High prio 
- [ ] Single-select dropdown

Med prio 
- [ ] Multi-select dropdown
- [ ] Slider (arbitrary range of values set by user)
- [ ] Checkbox (returns True/False to Python) 
- [ ] Date-picker 

+1 from recent user interview (3/1/2024)
+1 from recent user interview (7/9/2024)
(lots of other scattered non-power user feedback as well)

**Comment by davidkircos** [comment]
I think this makes sense as a data validation on cell values.

**Comment by luke-quadratic** [comment]
+1 from active team on being able to filter in the dropdown by typing search criteria 
![CleanShot 2024-07-21 at 16 07 47](https://github.com/user-attachments/assets/687f7ccc-4a66-461c-87e7-235e3118bddb)
