### ISSUE TITLE
bug: The drag canvas mode (spacebar) sometimes gets stuck until I repeatedly hit spacebar. 

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1142]
Reported by Franco via email. Using Orion 0.99 (WebKit 618.1.2) in MacOS Ventura 13.4.

Can we reproduce this bug?

**Comment by luke-quadratic** [comment]
have had this happen once or twice but I couldn't recreate at the time - naturally a refresh fixes (consider closing issue)

**Comment by luke-quadratic** [comment]
Reopen if still an issue - can no longer recreate and haven't experienced in months
