### ISSUE TITLE
bug: Black Screen on Firefox

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1143]
![image (12)](https://github.com/quadratichq/quadratic/assets/3479421/459ec20e-0176-48a0-bcd5-db65f1281e2b)

> I'm running Windows 11 and Firefox 123.0, with tracking protection set to "standard".
I've tried disabling Ublock Origin for this site, and the only other extension I have is Bitwarden. 

Can we reproduce this issue?

**Comment by luke-quadratic** [comment]
Related, I was originally Firefox only in the product and never had the black screen issue but did run into other issues such as: https://github.com/quadratichq/quadratic/issues/862

**Comment by luke-quadratic** [comment]
not reproducible
