### ISSUE TITLE
bug: Text Overflow

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1144]
![image (13)](https://github.com/quadratichq/quadratic/assets/3479421/4fafbc9c-f50e-492d-8cd1-9dfb3d4128e8)

**Comment by davidfig** [comment]
<img width="471" alt="Screenshot 2024-03-07 at 4 21 01 PM" src="https://github.com/quadratichq/quadratic/assets/442879/40061211-f3a8-4f39-8e40-ab7da657f079">

This looks like it's related to the cell box boundaries.
