### ISSUE TITLE
bug: code editor overlays sheet bar

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1148]
When you open the code editor, it will overlay the sheet bar. If you have lots of tabs, this makes them invisible and, in some cases, even unreachable.

![CleanShot 2024-03-04 at 12 32 27@2x](https://github.com/quadratichq/quadratic/assets/1316441/90ac35e1-88ca-475c-9fed-bbed9da9df62)

Maybe this is ok? The user can always just close the editor. And it gives a bit more vertical height for the editor.

But we could also just the sheet bar always visible.

![CleanShot 2024-03-04 at 12 33 02@2x](https://github.com/quadratichq/quadratic/assets/1316441/13234728-5d83-4e3a-b496-e923397d020d)

**Comment by davidkircos** [comment]
I think I like the sheet bar being behind. Although we should maybe narrow it's width so no tabs are "hidden behind" the code editor.

**Comment by luke-quadratic** [comment]
Not sure what solved but we merged a fix so now it works like this 

![Image](https://github.com/quadratichq/quadratic/assets/146771258/244df9e3-8534-4e83-be63-52d55c7ba909)
