### ISSUE TITLE
bug: duplicate sheet broken

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1152]
For this particular file, if I try to duplicate the main sheet, it breaks

https://app.quadratichq.com/file/4dc14273-8ef2-4dc9-afac-0f37ab36f64a

![CleanShot 2024-03-06 at 09 42 54@2x](https://github.com/quadratichq/quadratic/assets/1316441/12fc8670-b30d-4ecc-b765-07621441efb9)

**Comment by luke-quadratic** [comment]
No longer breaks on duplicate
