### ISSUE TITLE
Click line number to change what gets returned to cell 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1168]
Feedback from a full-time Python dev - click line number to edit what gets returned. 

![CleanShot 2024-03-11 at 09 54 09@2x](https://github.com/quadratichq/quadratic/assets/146771258/81b67e55-3166-4502-89b5-67a0330a1480)

**Comment by davidkircos** [comment]
You can always comment out lower lines to change the return. Clicking a line number seems like an odd interface for changing the return. A user could do accidentally, and it doesn't seem very initiative

**Comment by luke-quadratic** [comment]
Agreed on all - can reopen if someone thinks this is worthwhile/someone requests in the future
