### ISSUE TITLE
feature: Copy Paste Supports Formatting to GSheets / Excel

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1183]
Can copy paste basic formatting:
- Bold
- Italic 
- Text color
- Background color
- Borders

**Comment by davidfig** [comment]
https://github.com/quadratichq/quadratic/assets/442879/68e49d9b-a925-4ce5-8638-2c034a7fd137

**Comment by davidkircos** [comment]
Clarified in the title. This is for copy paste to outside of Quadratic into Sheets / Excel.
