### ISSUE TITLE
Getting started options: add import box or dropdown for quick-start import data files to sheet

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1195]
Help users get started by giving them option to create file from data import, would put the 0,0 data at 0,0 in sheet. Needs design but something along the line of what's attached to issue. 

![CleanShot 2024-03-19 at 10 10 07@2x](https://github.com/quadratichq/quadratic/assets/146771258/1c85f700-ab44-4985-b150-58186b4ae2dd)

**Comment by ddimaria** [comment]
We started discussing this yesterday, and think we have a path forward with routing the uploaded file from the dashboard into a new grid/sheet (similar to how we upload grid files IIRC).

**Comment by luke-quadratic** [comment]
We will be rethinking this soon in #1093
