### ISSUE TITLE
bug: relative cell outline references are wrong

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1217]
When you add a relative cell to the grid, the visual indicator of the position of that cell on the grid is wrong.

![CleanShot 2024-03-25 at 13 25 35@2x](https://github.com/quadratichq/quadratic/assets/1316441/f2dd14b0-2200-43b5-a4e7-418139343879)

**Comment by saraelsa** [comment]
I took a look at this issue.

It's actually a coincidence that relative cells are highlighted incorrectly; the root issue is that the cell reference detection algorithm is extremely liberal and detects all of these value formats:
- `c(...)`
- `e(...)`
- `l(...)`
- `s(...)`

The cell reference detection algorithm does not look for relatively references at all, and instead, misinterprets relative references as absolute references.

[Here](https://github.com/quadratichq/quadratic/compare/main...saraelsa:quadratic:python-cell-ref-parser-fixes) is a patch which implements relative referencing support.
