### ISSUE TITLE
Careers button on careers.quadratic.to leads to cloudflare blocked page

### ISSUE THREAD

**Issue by Perceval62** [quadratichq/quadratic#123]
Hi :D

## Issue description:
I just recently saw the paid ad for the «No Boiler Plate» youtube channel.
When I click on the "Careers" on the home page I get redirected or use the link in their description I get a blocked page.

## Steps to reproduce the issue
I'm based in Montreal Canada
and I simply accessed the home page and clicked on the careers button.
The bug is present on Firefox and Brave from what I tested

## Intended behaviour:
I assume since you guys are hiring, that you'd want people to land on some sort of form on :D

## Actual behaviour:
Check the image below

Edit: I didn't know where to post this, if this is not the correct space to inform of this bug, could you redirect me to the correct authority ?

Additional details / screenshots
![image](https://user-images.githubusercontent.com/31328738/191544604-ce171222-b169-411d-9ba3-51f59f52cc83.png)

**Comment by davidkircos** [comment]
Hey, thank you for reporting @Perceval62 

It was up a few minutes ago, I believe this was caused by a spike in activity from the video.

You can also view the careers page here:
https://pickle-act-ebf.notion.site/Join-Quadratic-Build-The-Next-Generation-Spreadsheet-480e18e3eb92413b96d8db989bc8d2a6

**Comment by Perceval62** [comment]
Thanks for the quick response :D
Your link worked perfectly.
Good luck with the activity spike ;)

**Comment by davidkircos** [comment]
Thank you!

**Comment by davidkircos** [comment]
I set up a temporary fix with the DNS, to redirect `careers.quadratic.to` directly to the `pickle-act-ebf.notion.site` link.

@Perceval62 does this fix work on your end?

**Comment by Perceval62** [comment]
I am getting redirected to something else than a cloudflare error page but the page takes forever to load.

**Comment by davidkircos** [comment]
Ok, that DNS fix did not work. 

I moved to a new host and this seems to work!

**Comment by Perceval62** [comment]
Yes it works perfectly now.

**Comment by Perceval62** [comment]
I'll close the issue since the problem is fixed !
