### ISSUE TITLE
feature: toggle borders

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1231]
When you're applying borders, such as "Border left", if the border is already there we turn it off. If it's not present we turn it on.

This is especially useful when you have some borders present but need fine-grained control over styling a particular border. For example, imagine you have a cell with borders on all sides

```
 -----
|     |
 -----
```

But you want to remove a border on just the left side

```
 -----
      |
 -----
```

To do this today, it requires multiple steps:

1. Clear all borders
2. Apply top border
3. Apply bottom border
4. Apply right border

However, if border controls allowed "toggling" then it would only be one step:

1. Toggle border left

**Comment by davidfig** [comment]
Jim's suggestion is what we do for toggling styles like bold. It's the most consistent behavior and should be implemented.
