### ISSUE TITLE
App crashes using shortcut to run all cells in sheet 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1264]
Seems to only be happening in sheets with one code cell. 

To recreate: 
create any sheet with only one code cell 
use shortcut to run all code cells in file (cmd+shift+return)
should crash within 5 seconds 

(might exist in other files where there are more than one code cell but this was only way I could recreate

**Comment by luke-quadratic** [comment]
Didn't notice until now but will be closed by #1253

**Comment by davidkircos** [comment]
Fixed in #1253
