### ISSUE TITLE
Numpy float64 renders as string

### ISSUE THREAD

**Issue by saraelsa** [quadratichq/quadratic#1275]
# Reproduction

In cell A, enter the following Python code:
```py
1.5
```

In cell B, enter the following Python code:
```py
import numpy as np

np.float64(1.5)
```

Note that cell A is right-aligned but cell B is left-aligned.

Try formatting both cells as currency. Note that only cell A is formatted as a currency value.

# Expected behavior

Numpy `float64` values are treated the same as standard `float` values.

# Observed behavior

Numpy `float64` values are treated as textual data.

**Comment by luke-quadratic** [comment]
This is awesome feedback - bumping up towards the top of our queue since I think it'd make a lot of sense to work on alongside #1086 

Thanks for the really well structured bug report @saraelsa, very clear!

**Comment by saraelsa** [comment]
Thanks!

I took a look at the code and I think I found the problem:
```py
# Convert from python types to quadratic types
def to_quadratic_type(value: int | float | str | bool | pd.Timestamp | date | time | datetime | pd.Period | timedelta | None) -> Tuple[str, str]:
    
    try:    
        if value == None or value == "":
            return ("", "blank")
        
        if type(value) == str:
            return (str(value), "text")
            
        value = ast.literal_eval(value)
    except:
        pass
    
    try:
        if type(value) == int or type(value) == float:
            return (str(value), "number")
        elif type(value) == bool:
            return (str(bool(value)), "logical")
        elif isinstance(value, (pd.Timestamp, np.datetime64, date, time, datetime)) or pd.api.types.is_datetime64_dtype(value):
            return (str(to_unix_timestamp(value)), "instant")
        
        # TODO(ddimaria): implement when we implement duration in Rust
        # elif isinstance(value, (pd.Period, np.timedelta64, timedelta)):
        # elif isinstance(value, pd.Period):
        #     return (to_interval(value), "duration")
        else :
            return (str(value), "text")
    except:
        return (str(value), "text")
```
(from `quadratic-kernels/python-wasm/quadratic_py/utils.py`)

this function only compares the type against native `int` and `float` types here:
```py
if type(value) == int or type(value) == float:
```

We can add a check for Numpy's number values. There are several, but they all derive from `np.number`, so the check can be done as follows:
```py
if type(value) == int or type(value) == float or isinstance(value, np.number):
```

(with `np.number` also added to the parameter's type annotation)

**Comment by davidkircos** [comment]
Yeah, this approach sounds good to me!
