### ISSUE TITLE
feat: Have files be searchable in browser url by name

### ISSUE THREAD

**Issue by N-Demir** [quadratichq/quadratic#1301]
Hopefully I'm describing this well, but I noticed that it's easy for me to find google sheets from my browser because typing in the sheet's name ("Project Tracker" e.g.) in the browser url pulls up the sheet, but quadratic spreadsheets don't have their names in that url area and so I have to usually go to the files browser to find which spreadsheet I'm looking for in particular

Example with a google sheet:
<img width="905" alt="Screenshot 2024-04-23 at 10 02 13 AM" src="https://github.com/quadratichq/quadratic/assets/23620644/ab4d727d-b619-413f-a393-4ee342fafc50">

Example with a quadratic sheet:
<img width="891" alt="Screenshot 2024-04-23 at 10 03 00 AM" src="https://github.com/quadratichq/quadratic/assets/23620644/e3837354-c913-448b-81f3-e979501139e0">

**Comment by N-Demir** [comment]
I think you guys added this so I'll close it! Thank you!!!

**Comment by davidkircos** [comment]
Oh does this work now? I think when you open a file the name is in the page `title`. And Chrome makes these searchable.

**Comment by N-Demir** [comment]
Yeap seems to work on chrome and safari for me now!
