### ISSUE TITLE
Can’t right-click row/column headers to do common operations like modify/delete row/column

### ISSUE THREAD

**Issue by dhruvpatel015** [quadratichq/quadratic#1325]
Can’t right-click on rows or column headers to do common operations like modify/delete row/column. We also can't wrap text which is kinda annoying.

**Comment by luke-quadratic** [comment]
Hey thanks for the comment, gonna bump some of this stuff up cuz it's been common feedback recently for modify/delete etc 

Hadn't heard the wrap text feedback until now so will note that down to increase its priority 

**Note the duplicate issues:** 
For modify/delete/move rows and columns - https://github.com/quadratichq/quadratic/issues/1072
For wrap text - https://github.com/quadratichq/quadratic/issues/1227

**Comment by luke-quadratic** [comment]
Closed as duplicate. 

#1072 
#1227
