### ISSUE TITLE
Dotted line borders are not placed correctly

### ISSUE THREAD

**Issue by nathancarter** [quadratichq/quadratic#1326]
When editing a cell containing a Python formula, if you write `rc(5,2)` it correctly highlights the cell 5 to the right and 2 below.

But if you were to write `c(5,2)`, it highlights the same cell, as if it thinks that is a relative reference, when it is not.

Even worse, if you write `range(1,10)`, it highlights the cell 1 to the right and 10 below!

**Comment by luke-quadratic** [comment]
Thanks for the bug report - I'm struggling to recreate the c(5,2) highlighting not working as well as range not working. It seems to me c(5,2) gets correctly highlighted and range highlights nothing. There is a little visual oddity on my end when you click play where it flashes though. 

![CleanShot 2024-04-29 at 14 08 12](https://github.com/quadratichq/quadratic/assets/146771258/5ed3c559-9d3f-4e16-9b9b-7650d6de94a6)

**Comment by nathancarter** [comment]
Ah, sorry.  My students and I made a list of bug reports in one class, then submitted them during the next class.  We didn't expect you had fixed them in between the two class periods!  Yes, I can verify it works on my end, but I will also point out that it works only after you execute the cell.  That is, it does not create the highlights while typing the Python code, but only after running it.  (To be consistent with what users expect from spreadsheets, I'd expect it would be watching while we type.)

**Comment by davidkircos** [comment]
Thanks @nathancarter !

The way we detect which cells the code references relies on running the code to get it absolutely correct. You can imagine if you used a random number to reference a cell, you couldn't highlight cells before actually running the code. That said, we have it on our list to auto highlight all obvious cell references that use x, y ints to reference a cell - in realtime like you'd expect.
