### ISSUE TITLE
Inequality comparison issue using <> logic

### ISSUE THREAD

**Issue by Bill2464** [quadratichq/quadratic#1328]
When attempting to use the not equal to logic "<>" in the formula portion of quadratic we get the following error:

Example Code: IF(C23 <> 1, 11, 22)
Result:
ERROR: colum 14 to 15: Expected expression

We think this is due to quadratic reading the less than sign (<) seperately from the greater than sign (>) rather than holistically as (<>)

**Comment by luke-quadratic** [comment]
Good catch, we'll get this fixed! 

![CleanShot 2024-04-29 at 14 13 48@2x](https://github.com/quadratichq/quadratic/assets/146771258/8d7a3f4a-488c-4e58-a0f6-0d4536ba8a37)
