### ISSUE TITLE
Press / to code indicator update 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1351]
Been playing with this hint more and more lately on fresh accts for preview branches, it's a little annoying how it follows you around - I think updating alongside or after our Inline Formulas updates makes sense 

Proposed update: 
- Every new sheet would have the text in the 0,0 cell until an action is done 
- Any action anywhere in the sheet removes the hint 
- Proposed text: "Type / to code or = to write formulas" with no '' around the / or =, unlike how it is currently

**Comment by davidkircos** [comment]
This makes sense to me. I also find it annoying, but I use preview branches a lot. I think it's most likely helping more people than annoying them in production where they only see it for a short time, then never again.
