### ISSUE TITLE
Press / to code from within cell 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1360]
When cell is in focus in text we open the code selection menu with = 

Now that we're going away from = to / we never updated / to have this same behavior. If you hit / without any text in the cell it doesn't pull up code select. Should only happen when there's no other text in the cell. 

![CleanShot 2024-05-16 at 14 52 18](https://github.com/quadratichq/quadratic/assets/146771258/bcb1e4b4-6b6d-4436-a52a-fa1e7983a92e)

**Comment by davidfig** [comment]
This should work in the inline-formula branch
