### ISSUE TITLE
Inline formulas hint for multi-line carries over across sheets 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1364]
If you switch sheets while formula is open the UI for opening multi-line editor will drag over 

![CleanShot 2024-05-20 at 11 24 14@2x](https://github.com/quadratichq/quadratic/assets/146771258/7602cb53-58c7-4d8e-b674-3218b016af5c)

**Comment by davidfig** [comment]
This is fixed in the PR
