### ISSUE TITLE
bug: flash of deleted content

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1366]
This is minor, but it does feel weird that you get this flash of a previous value.

Steps to reproduce:

1. Go to a cell
2. Type "12="
3. Hit enter
4. Hit up key to go back to cell
5. Hit "Enter" to edit the cell
6. CMD + A to select its contents
7. Delete to remove all text
8. Hit enter
9. See flash of previous text

https://github.com/quadratichq/quadratic/assets/1316441/e81a4cba-b762-4bd4-8e6e-e7c1dea334e5

What's strange is it only happens _sometimes_. If you don't see it, try running these steps over and over until you do.

**Comment by luke-quadratic** [comment]
I believe this was fixed in #1661 as I can no longer recreate
