### ISSUE TITLE
bug: text cursor stuck on after closing cell

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1374]
How to reproduce 
1. press enter on a cell
2. type "asdf"
3. press enter to submit
![CleanShot 2024-05-21 at 20 30 52](https://github.com/quadratichq/quadratic/assets/3479421/17aabb40-73d7-4e20-9b42-926aa9d98485)

**Comment by davidfig** [comment]
I'm not seeing this on my machine.

**Comment by davidkircos** [comment]
Try it in production

**Comment by davidkircos** [comment]
This bug disappears with the latest Chrome update
