### ISSUE TITLE
Hitting tab multiple times not working

### ISSUE THREAD

**Issue by N-Demir** [quadratichq/quadratic#1384]
Recreate: I'm writing in a cell and i hit tab, my focus switches to the next cell, but also 'Add Sheet' shows up. Weird, but also now I can't press tab to keep moving sideways. 

<img width="319" alt="Screenshot 2024-05-28 at 4 50 06 PM" src="https://github.com/quadratichq/quadratic/assets/23620644/9fd2b170-9a31-4a33-a6fe-9825cce8c29f">

I'm on brave

**Comment by davidkircos** [comment]
Verified this bug also exists in Chrome.

Thanks for reporting!
