### ISSUE TITLE
Reference generic Python Classes

### ISSUE THREAD

**Issue by KwentiN-ui** [quadratichq/quadratic#1420]
First of all, I want to express that this product looks extremely promising and I'm excited to see where this is going.

However, coming from more of an engineering than data science background, I often find myself writing classes for Cross-sectional-profiles or mechanical parts. These would need to be accessed globally, or at least by reference in different cells.
From a user perspective, I would imagine something like this:

1. User writes custom class/defines Data Structure inside a cell
2. Python Document is given a name `custom_name` through the editor
3. User switches to cell to reference object
4. Import custom object through defined namespace `from .custom_name import object`

Alternatively, being able to reference an object by cell would be a more manual process. Although I assume this is not as easily implemented given the string parsed nature of cell references.

**Comment by luke-quadratic** [comment]
@KwentiN-ui This is great feedback and noted - going to group this alongside #1115 in our roadmap. 

We've been hearing more and more similar comments on code reuse lately; your comment here is a welcome differing approach from what many have proposed. It's definitely around the corner for us to think about how code reuse will work. The actual building of this feature is more simple than thinking through the correct way for this to work. 

To me, dedicated code files whose classes, functions, etc are by default global to every sheet in a file is an intuitive approach. You could imagine these dedicated sheets as the equivalent of a single 'cell' in a jupyter style notebook. When you create a new tab in the bottom you're asked if you want to create a new normal sheet or if you want to create one of these dedicated global code notebook cells. Is this roughly along your thinking by saying "Python document?" 

(a lot of these interactions are better described visually haha)

**Comment by KwentiN-ui** [comment]
This is great to hear! When I thought about a possible implementation of this feature I had the exact same idea of having some sort of `__init__.py` file connected to the document, but changed my mind in favor of simply naming python cells in the editor window. Although it would be awesome to just upload an existing project directory and use its custom classes in a given document.

**Comment by jimniels** [comment]
Closing as a duplicate. Will continue discussion of this issue in #1115
