### ISSUE TITLE
Improve multiplayer and offline experiences

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1439]
Users who spend time away from the app for a long time come back and can still use the sheet but their work doesn't save because they're not reconnected to multiplayer. 

- [x] add indication when not connected to refresh
- [x] rehydrate auth if auth token outdated
- [x] better visual indicator for mulitplayer status and syncing
- [x] popup when offline for > n seconds so it's clear

**Comment by ddimaria** [comment]
For security reasons, I don't think we want to auto-refresh the token.  Since we store unsent transactions in local storage, we could simply log the user's out when this happens, then the transactions would be sent off upon login (if applicable).
