### ISSUE TITLE
papercut: column selection and insert range into Python, Formulas, and JS don't work together

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1445]
[on hold until finite sheet]

Disabled in menu

- [ ] be able to reference a column in Python/row in Python (and js)
- [ ] be able to select rows/columns into Python via column/row selection (and js)
- [ ] be able to do operations in Formulas on rows/columns 

![CleanShot 2024-06-20 at 15 28 53@2x](https://github.com/quadratichq/quadratic/assets/3479421/3fb07280-be91-4bbc-a4f0-4adcb9d10d98)
![CleanShot 2024-07-26 at 12 14 29](https://github.com/user-attachments/assets/eae17b0e-f301-4c7e-8b24-961b59df8eb9)

**Comment by luke-quadratic** [comment]
from your comments in Slack, something like this probably makes the most sense, as column selection is infinite 

`data = cells(column=1)`

Noting that this also gets partially solved if column and row selection worked like select all where the second button press of a column or row selected just the cells with content

**Comment by luke-quadratic** [comment]
This now works in A1/negative space 

syntax: q("A:A")

**Comment by luke-quadratic** [comment]
Closing as not relevant as path forward resolved and duplicate issue for #1629, will be solved in that
