### ISSUE TITLE
papercut: things rendered under code editor do not rerender when editor is closed. disappear, then reappear on move

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1446]
![CleanShot 2024-06-20 at 15 47 42](https://github.com/quadratichq/quadratic/assets/3479421/61589302-339e-4454-8f6c-31afab884c39)

**Comment by davidfig** [comment]
I can't replicate this.

**Comment by davidfig** [comment]
This is still a bug. I was able to replicate it with Ayush's steps. Should be a minor fix.

**Comment by AyushAgrawal-A2** [comment]
> This is still a bug. I was able to replicate it with Ayush's steps. Should be a minor fix.

@davidfig 
fixed in #1513, so issue can be closed I guess
