### ISSUE TITLE
bug: editing a cell with text while code editor is opening prompts to save changes

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1457]
If you have the code editor open (with some changes) and then you try to edit another cell with just text, it prompts you to "save changes" as if it's going to close the editor. But if you choose "cancel" you can continue editing the cell with text that you just started.

https://github.com/quadratichq/quadratic/assets/1316441/15906a54-602a-4ae5-ba1b-4e7a720dce03

**Comment by davidfig** [comment]
Fixed
