### ISSUE TITLE
bug: resizing issues

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1460]
See video:

https://github.com/quadratichq/quadratic/assets/1316441/700e77a0-b31b-477e-a097-5aa5369ed0ac

**Comment by jimniels** [comment]
Resizing the columns in the source data for this sheet seems to break rendering pretty easily (like resize a column and watch the trimming work, then go try to edit a cell and see that the rendering position ends up off — you have to then refresh to fix it).

https://app.quadratichq.com/file/c7f21ff2-0459-46cc-a965-f21d111d220e

**Comment by luke-quadratic** [comment]
Formatting also has issues with resizing - 

![Image](https://github.com/quadratichq/quadratic/assets/146771258/4700088e-77cb-45ae-9def-13a7252bb28b)

**Comment by AyushAgrawal-A2** [comment]
> Formatting also has issues during resizing -
> 
> ![Image](https://private-user-images.githubusercontent.com/146771258/345212274-4700088e-77cb-45ae-9def-13a7252bb28b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Njc4MzAsIm5iZiI6MTcxOTk2NzUzMCwicGF0aCI6Ii8xNDY3NzEyNTgvMzQ1MjEyMjc0LTQ3MDAwODhlLTc3Y2ItNDVhZS05ZGVmLTEzYTcyNTJiYjI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwMDQ1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzRmZTQ1N2FhY2Q5MDdkN2FiYTQ5ZTc3Mjc2NDI1YWJkNjMzYjYyNWMzYWVmNjk1MTczNmQ0YjFkYzQ0YTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OCaE3IqC_ej8In-n56PTbazGZL6Ze8_WdjmkZw9v0hw)

@luke-quadratic 
this is also fixed in #1406
