### ISSUE TITLE
No cell drag box when code editor is open 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1486]
Javascript branch introduces this lack of a box on the cell outline. 

How it used to be: 
![CleanShot 2024-06-27 at 14 25 17](https://github.com/quadratichq/quadratic/assets/146771258/27129b5d-d611-4fa5-a643-04fca7f25087)

Now there's no box to click and drag from when the code editor is open - reintroduce this.

**Comment by davidkircos** [comment]
We decided to keep it hidden on the currently edited cell.
