### ISSUE TITLE
Allow inline formula editing while editing a code cell 

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1489]
You can create a new formula cell when a code cell is open. If you try to edit an existing one it will close the code editor. This feels inconsistent.

- [ ] allow editing of inline formula when code cell editor is open
- [ ] Fix bug where codecellcursor disappears when editing an inline formula

**Comment by AyushAgrawal-A2** [comment]
> - [ ] Fix bug where codecellcursor disappears when editing an inline formula

@davidkircos 
how to reproduce this ?

**Comment by davidkircos** [comment]
already in main
