### ISSUE TITLE
Code selector is inaccessible in Firefox

### ISSUE THREAD

**Issue by HactarCE** [quadratichq/quadratic#1499]
Pressing <kbd>/</kbd> to open the code selector also opens "quick-find" in Firefox. The first time it's pressed, it opens the code selector _and_ the quick-find, but focuses the quick-find popup, which removes focus from the grid and causes subsequent keystrokes to be lost. This is particularly devious because quick-find is so subtle at the bottom of the screen, so just seems like the keyboard stops working after pressing <kbd>/</kbd>.

I believe this is a significant accessibility issue, since I can't find any other way to open the code selector.

Actions we need to take:
- Add some way to open the code selector with the mouse (for accessibility)
- Override the quick-find keybind in Firefox, or add an alternative keybind

**Comment by davidkircos** [comment]
This may be because the function is called `async` here https://github.com/quadratichq/quadratic/blob/f1926e9aa6feb11a2b7f5297fac8974e1253de2e/quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCell.ts#L29

I believe to prevent default we need to have this function be synchronous

**Comment by davidkircos** [comment]
> Pressing / just open the quick find in firefox on Linux. It does not open the code selector. (I'm on a French keyboard where / is accessible through SHIFT only).

Hello @ghislainp thanks for the feedback, we are going to make it so that Shift + / also opens the code selector menu.
