### ISSUE TITLE
bug: applying offline transactions after reloading a document, fails silently

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1519]
1. Open a file
2. Wait until auth token expires (24hrs)
3. Return, multiplayer should show "Connecting..."
4. Make some changes
5. Reload
6. Changes are lost silently

**Comment by davidfig** [comment]
What does multiplayer footer message show in these scenarios? I can't see why it wouldn't save to the offline storage regardless of the multiplayer connection.

**Comment by davidkircos** [comment]
It just shows "Connecting..." no other helpful information in console or in UI

**Comment by luke-quadratic** [comment]
Bumped up to high prio on user losing work progress because of original steps taken in @davidkircos original bug report. 

I know we had discussed possibility of just force reloading a stale connection, either way this should become a high prio issue.
