### ISSUE TITLE
Ctrl + arrow key should go to the ending cell in a group that has data

### ISSUE THREAD

**Issue by deshumake** [quadratichq/quadratic#154]
A feature that all other spreadsheets have that is currently missing

ctrl + shift + arrow should multiselect

**Comment by jimniels** [comment]
This has been implemented in the app (gif showing `CMD` + arrow [+ shift] on mac)

![May-17-2023 13-58-20](https://github.com/quadratichq/quadratic/assets/1316441/e5f7d628-9b4b-4ad5-a39f-c1e31bdebc7f)
