### ISSUE TITLE
Confusing Behavior When Dragging Code Output Without Source Cell

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1546]
See video

Maybe some sort of warning when you do this? Or prevent it by default? Not sure.

https://github.com/quadratichq/quadratic/assets/3479421/437b5ccc-29cc-4a8f-a0cd-902be761b175

**Comment by davidfig** [comment]
That's a bug. nothing should move there

**Comment by davidkircos** [comment]
Better captured in other issues.
