### ISSUE TITLE
Undo and Redo Functionality Missing

### ISSUE THREAD

**Issue by deshumake** [quadratichq/quadratic#155]
Never implemented something like this before. Any ideas on how?

First guess would be to just have a stack of actions taken, and then move back and forward on that stack

**Comment by dk8996** [comment]
@deshumake Maybe a command pattern would work here you would also need `undo` and `redo` stacks/collections. 

```
interface Command {
 execute() {}
}

interface Undoable {
undo() {}
redo(){}
}

AddTextCommand implement Undoable, Command {
  private currentState;
  private newText;
  constructor(newText) {}
  execute() { 
// Save the currentState
//Apply changes

} 
  undo() {}
 redo() {}
}

```

**Comment by davidkircos** [comment]
We are working on Undo/Redo in the `development` branch. You can check out the pr here #147 

Using a Transaction that contains Commands. Undo stack gets added with inverse transactions. You can see how this works in the `SheetController`
