### ISSUE TITLE
API requests proxy service not working 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1565]
![CleanShot 2024-07-18 at 12 54 05@2x](https://github.com/user-attachments/assets/2367e2d8-3e0d-40a1-a877-43192a18939a)

**Comment by ddimaria** [comment]
We have tightened restrictions on custom headers in the connections service (generally a good practice), but need to remove the restrictions if we want to allow users to send custom headers to the proxy.  We currently just pass along headers from the client to the end service, so allowing all headers will fix the issue.  

A possibly more robust option is to serialize all user request headers in a custom header, then deserialize and place into the headers to the target endpoint.
