### ISSUE TITLE
bug: javascript return type line number indicator is wrong

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1666]
In Python, the line being returned is marked with the appropriate arrow (line 4)

![CleanShot 2024-08-07 at 14 03 55@2x](https://github.com/user-attachments/assets/c48a0be2-5763-46a1-a712-ab13319954e6)

But in JavaScript, the line with `return` is not marked correctly (in this case, line 8 is marked with the arrow when it should be line 5)

![CleanShot 2024-08-07 at 14 04 11@2x](https://github.com/user-attachments/assets/cca1064d-65e0-4ee6-8396-a95145e89e5b)

For the above screenshot, the `evaluationResult` is: 

```
{type: 'number', value: '50', line_number: 103, output_type: 'number'}
```

**Comment by davidfig** [comment]
This is caused by my hack in tracking line numbers. In loops, it'll add the number of loops to the line number. I need to parse the loops to have it work properly (somehow).
