### ISSUE TITLE
bug: getCells broken in Safari

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1675]
Cell references are broken in Safari due to the SharedArrayBuffer issue

![CleanShot 2024-08-08 at 13 03 25@2x](https://github.com/user-attachments/assets/4f11c89f-5c98-4c3d-8dc8-723710335021)

**Comment by anthonycorletti** [comment]
Sad to see this 😢 I hope safari is supported again soon!

<img width="1367" alt="Screenshot 2024-08-26 at 8 14 05 PM" src="https://github.com/user-attachments/assets/08fed48c-d36d-4aa2-9a5d-f7a36d2c9e20">

**Comment by davidkircos** [comment]
Should be! The fix is under review

https://github.com/quadratichq/quadratic/pull/1677
