### ISSUE TITLE
Precision for Formula results resolving to huge numbers

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1678]
In prod we round properly, in QA we introduced something that is causing us to have these huge numbers by default on Formula results

To replicate:
`=AVERAGE(1,1,3)`

![CleanShot 2024-08-08 at 17 12 10](https://github.com/user-attachments/assets/308d4b55-6cf7-47c4-9a6d-60424a5f75fd)

**Comment by AyushAgrawal-A2** [comment]
Precision also looks bad here, after decimal all digits should be 6 and last 7.
