### ISSUE TITLE
nit: code cell overflow display bugs

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1721]
Steps to reproduce:

1. create a python cell with overflow
2. drag that so there are lots of overflow conflicting cells
3. sheet is not drawn correctly. 

oddly on undo / redo it is drawn properly

https://github.com/user-attachments/assets/85d9c4f6-a3f8-4b47-8563-d1b15af8c5da

**Comment by AyushAgrawal-A2** [comment]
@luke-quadratic 
this is fixed in QA, pls verfiy

**Comment by luke-quadratic** [comment]
Verified - fixed
