### ISSUE TITLE
nit: don't wait for python to load before opening a file

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1730]

**Comment by davidfig** [comment]
I don't think we're doing this.

**Comment by davidkircos** [comment]
One of @AyushAgrawal-A2 changes made it if there is offline transactions, wait until Python loads to open the file. Also possible happens if the file is behind the last checkpoint, it loads python and those transactions before loading the document.

**Comment by davidfig** [comment]
Offline transactions should not call compute again. They only save the results.

**Comment by AyushAgrawal-A2** [comment]
@davidkircos 
I checked again, there are 2 operation when running code. ComputeCode and SetCodeRun. ComputeCode requires python, SetCodeRun is just saving the result of code run. ComputeCode is not saved into offline transactions, so while loading offline transactions, page will not wait for python load.
Sorry I was mistaken before, @davidfig is correct.
