### ISSUE TITLE
bug: moving formula with multi cursor incorrectly shifts formula references

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#1731]
Edit: this issue exists for copy-pasting formulas across sheets as well 

**To fix:** 
- [x] Dragging references 
- [x] Copy pasting references across sheets 

https://github.com/user-attachments/assets/c7d2bb32-0cc4-4f5e-b6b3-63cfb04929e3

**Comment by luke-quadratic** [comment]
Fix works as intended
