### ISSUE TITLE
Bug: stuck in cursor grabber mode 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1738]
At the moment if you use the app for a bit of time there's a high probability you get stuck in the state where your cursor is a grabber cursor and the sheet is basically bricked. 

![CleanShot 2024-08-20 at 11 39 38@2x](https://github.com/user-attachments/assets/70428f1f-31c3-4547-a4bb-be603aa47838)

Potential solution [@davidkircos ]
- This is likely caused by the space bar up event not being triggered where it needs to be
- Whenever drag mode is activated, make sure the keboard.space is pressed on each mouse move event and if it's not, deactivate drag mode.

**Comment by davidfig** [comment]
+1 on this one

**Comment by AyushAgrawal-A2** [comment]
Not able to reproduce

**Comment by luke-quadratic** [comment]
Bug disappeared somehow after being pervasive, will re-open if discovered again
