### ISSUE TITLE
Scaling/zooming the whole web page (i.e. the whole UI) does work badly

### ISSUE THREAD

**Issue by dumblob** [quadratichq/quadratic#175]
Platforms with high-res displays and platforms for partially sight-disabled people require one to have a >100% default zoom.

Quadratic though works really badly on e.g. 150% zoom. The dialogue(s) goes off-screen a lot, etc. Also zooming with Ctrl+scrolling seems disabled for unknown reason.

Please fix this "non-responsiveness" and accessibility issues. Thanks!

**Comment by davidkircos** [comment]
Hello @dumblob ,

Could you please share screenshots of dialogues going off-screen? 

Ctrl+Scroll works on Mac on the grid. Are you on Windows?

Thank you for your feedback! Happy to make Quadratic a more accessible app.

**Comment by dumblob** [comment]
Oh, now I noticed I have not been clear enough. I am sorry for that. With web page I meant https://www.quadratichq.com/ and not the app itself. It looks like this in Firefox (and nearly identically in Chromium):

![20230106_202628+0100-1680x1050+0+0-imlib2_grab](https://user-images.githubusercontent.com/2451044/211087298-f6730047-28ff-413c-a194-bd286fe005f0.png)

The app itself seems more or less OK with higher scales (~160% is the max I have tried on notebook screens).

**Comment by davidkircos** [comment]
Ah, thanks for the clarification! Yes, this is an issue.

**Comment by flbn** [comment]
is there a repo for the site? i found a fix changing the styles, but was only able to do so using dev tools...
basically removed the absolute and fixed positions, replaced with a grid and a grid template: 'header main footer'

body has an overflow-y set to scroll

header becomes a flex (justify between, align items centrally)

footer gets some margin between the main grid-area

pretty simple, obviously not the focus but to fix this ticket you could do something similar

**Comment by jimniels** [comment]
There's a repo for the website, but it's not public (perhaps we can considering making it so...)

We've since launched a new version of the website, so the above issues are no longer relevant. Going to close this issue...
