### ISSUE TITLE
bug: option + arrow doesn't work for moving cursor position in AI assistant cell

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1766]
When you're trying to move the cursor from one word to the next using option + arrow left/right that event doesn't register with the textarea.

https://github.com/user-attachments/assets/f35b42fc-8c35-4ddc-9c78-20a3bf1f0859

**Comment by AyushAgrawal-A2** [comment]
Works for me

**Comment by jimniels** [comment]
Really? That's weird. It still doesn't work for me.

I was playing with some more things in the app with this and I think the issue is that the grid is stealing some shortcuts.

Try a file that has a space in the name and doing option + arrow left/right to move the cursor in the input field when you're renaming a file.

Note here in the video how cmd + arrow works to go to the end/beginning of the input, but option + arrow left/right doesn't work to move the cursor in the text input. Instead it actually moves the cursor on the sheet!


https://github.com/user-attachments/assets/9ee995c1-6226-4a19-8690-f4ce358efb7c

**Comment by AyushAgrawal-A2** [comment]
This is a problem in many places, the keydown event handler for grid is actually on the window object, it steals a lot of events.
I disabled on such event in this PR https://github.com/quadratichq/quadratic/pull/1752 but we cannot keep adding `event.preventDefault` and `event.stopPropagation` everywhere... I strongly think this should event listener should not be on window object, and use of window object should be avoided as much as possible. I'll move viewport event handler to the `QuadraticGrid` component where other listeners are present.
