### ISSUE TITLE
bug: passing a bad `sheetId` params in javascript getCells puts you in an infinite loop

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1767]
If I pass the wrong param for `sheetId` (e.g. a boolean instead of a string, or a sheetId that doesn't exist) then run the code, it just get stuck spinning, never telling me that I passed the wrong value.

![CleanShot 2024-08-22 at 15 32 07@2x](https://github.com/user-attachments/assets/d2c4b898-ddf1-4650-8018-90dbf6d206ff)

For example:

`let df = getCells(0, 9, 1, 12, true)` 
that gets me stuck in an infinite spinning state

`let df = getCells(0, 9, 1, 12, 'sheet that does not exist')`
that also gets me stuck in an infinite spinning state

`let df = getCells(0, 9, 1, 12, 'Sheet 1')`
this works

`let df = getCells(0, 9, 1, 12)`
this works

**Comment by luke-quadratic** [comment]
This fix works but the error received is quite strange, should this be blocking or is it a big adventure to fix @AyushAgrawal-A2 

![CleanShot 2024-08-27 at 17 40 29@2x](https://github.com/user-attachments/assets/25cca5cf-e2c9-44ce-8022-77e7e14939b0)
