### ISSUE TITLE
Horizontal scrolling using Shift+scroll

### ISSUE THREAD

**Issue by dumblob** [quadratichq/quadratic#177]
### Motivation

Spreadsheets have largely been the most common app users need to navigate horizontally. Unfortunately Quadratic seems to only offer horizontal scrolling by arrow keys navigation. So quick mouse navigation is not possible (there are no scrollbars which is IMHO a good UX decision but there must be a "mouse way" to scroll horizontally without putting your hand elsewhere from the mouse).

### Envisioned solution

Make `Shift+scroll` work as horizontal scroll :wink:.

**Comment by davidkircos** [comment]
@jimniels what do you think of adding this?

**Comment by jimniels** [comment]
Makes a lot of sense to me.

I've been using a magic mouse / trackpad for so long, I have no sense for physical scroll wheels on mice anymore. Surely this is a thing in other apps? e.g. does Figma allow horizontal scrolling/panning with SHIFT + scroll?

**Comment by dumblob** [comment]
> Surely this is a thing in other apps?

Yeah, it is very widespread. It originates from Microsoft Windows IIRC.

>e.g. does Figma allow horizontal scrolling/panning with SHIFT + scroll?

IDK but you may try other apps - actually no need to go far away as all web browsers I know of have Shift+scroll as default :wink:.

**Comment by dumblob** [comment]
Awesome. Thanks a lot!
