### ISSUE TITLE
Remove flashes of content 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1842]
They're subtle but wear on a user over time in terms of perceived quality and stability. Note the flashes you get any time you confirm content, focus on a cell, etc. 

https://github.com/user-attachments/assets/ceee5b59-1003-4339-b182-33d1ade62311

**Comment by luke-quadratic** [comment]
Another flash happening around 0,0 

https://github.com/user-attachments/assets/11bdf8df-c902-43b4-9c0b-b0783cfa986d

**Comment by luke-quadratic** [comment]
Data validation flash
[Screencast from 19-09-24 05_38_05 PM IST (2).webm](https://github.com/user-attachments/assets/7748183e-7a68-4820-aef6-8119b9be29c7)

**Comment by AyushAgrawal-A2** [comment]
>Another flash happening around 0,0

fixed in https://github.com/quadratichq/quadratic/pull/1972

**Comment by luke-quadratic** [comment]
#1972
