### ISSUE TITLE
QA: borders losing to selection outline 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1843]
Incorrect, current QA behavior 
![CleanShot 2024-09-04 at 15 26 31](https://github.com/user-attachments/assets/f4db9c30-9dfd-4a9e-b8dd-e60cd46836cc)

Correct, current prod behavior
![CleanShot 2024-09-04 at 15 27 27](https://github.com/user-attachments/assets/fc4a5543-8b03-4e54-a540-d3fc75cd953b)

**Comment by AyushAgrawal-A2** [comment]
@luke-quadratic 
Works for me in QA
[Screencast from 05-09-24 11:00:06 AM IST.webm](https://github.com/user-attachments/assets/2a51a6aa-731e-4bc9-8526-465ccda00c13)

**Comment by luke-quadratic** [comment]
Fixed from QA, doesn't exist in either QA or prod.
