### ISSUE TITLE
Unable to scroll in AI assistant in code editor 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1853]
Can't scroll to grab the selection I want in AI chat box 
![CleanShot 2024-09-06 at 16 07 29](https://github.com/user-attachments/assets/3a43acf7-bf2e-436a-8a98-87c7a53a756c)

**Comment by AyushAgrawal-A2** [comment]
@luke-quadratic 
duplicate of https://github.com/quadratichq/quadratic/issues/1768
