### ISSUE TITLE
bug (multiplayer): unfollowing from the grid doesn't work

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#1959]
If you follow and unfollow someone from the header (using their avatars), the state of them following you properly updates.

But if you follow someone from the header, then unfollow them from the control on the grid, then it still shows them as following you (see recording, note how when I click "stop" from the controls on the grid, the fact that I'm following them doesn't update for the other user — I have to go follow/unfollow again from the header to see it update appropriately)

https://github.com/user-attachments/assets/4cab74f1-45f1-4853-ae83-7c3b677deaae

**Comment by AyushAgrawal-A2** [comment]
@jimniels 
not able to reproduce

**Comment by jimniels** [comment]
@AyushAgrawal-A2 I thought it was a sequence, but it's actually a different bug. Updated the description.
