### ISSUE TITLE
Trouble importing CSV files.

### ISSUE THREAD

**Issue by paulwrath1223** [quadratichq/quadratic#1965]
On Ubuntu 24.04, and latest stable chrome, I am unable to drag CSV files in to the grid. (especially annoying when importing through the insert tab just tells you to drag and drop the file)

However, I can still select a CSV as the source when creating a new sheet and this works... Except it doesn't parse my CSV correctly. My CSV uses semicolons as the separator, and granted, that's pretty stupid when it's literally called "Comma Separated Values", but this is the standard for PCB component bill of materials, being exported that way in Fusion 360 and KiCad.

In any case, google sheets is able to parse it fine with automatic detection, and even lets the user specify the delimiter.

If it's not already implemented in the dev branch, I can take a crack at the automatic delimiter detection and put in a PR. My idea is to try to parse it using commas first, but if the rows have different lengths, try semicolon and tab (\t).

I could also look into drag and drop on Linux, but this is my first week of using Linux, so I don't think I would be much help.

**Comment by davidkircos** [comment]
Which browser are using where drag and drop doesn't work?

**Comment by AyushAgrawal-A2** [comment]
@paulwrath1223 
Hey, I am on Ubuntu 24.04 and I am able to drag/drop CSV files. For me it works on Google Chrome and Brave browser
Below is the screen cast showing a drag / drop of a 100k row sample CSV file. I use this daily as a test for performance regression for my PRs.

[Screencast from 2024-10-12 12-38-21.webm](https://github.com/user-attachments/assets/d1dd9f79-cab1-4697-9dcc-e1dea373b5f8)

Happy to debug and solve the issue you are facing, but I need more details on how to replicate it.

**Comment by paulwrath1223** [comment]
Hey guys, Im actually having a more insidious problem now. Dragging and dropping is still hit-and-miss, and I don't know how to replicate the state that makes it fail, but see attached video.

[Bug video](https://youtu.be/6fjoxOd7-nQ) (too big for GitHub attachment)

I swear I'm not copying and pasting.

Chrome Version 129.0.6668.100 (Official Build) (64-bit)

**Comment by paulwrath1223** [comment]
Can confirm that text typed in a password field in another tab is still picked up but converted to `••••••••`

**Comment by AyushAgrawal-A2** [comment]
@paulwrath1223 
I'll need more help from you to debug this:
1. For drag/drop failures, when it stops working can you please check the console for errors and please share with us. It is possible that the app kernel panicked or there is some other error thrown there.
2. For the text pasting bug, are you using middle mouse button to pan the canvas ? In Ubuntu, middle button is a global shortcut to paste last text selection. We should prevent this default behaviour on Ubuntu inside out App. Please confirm is that it or there is some other bug.

**Comment by paulwrath1223** [comment]
Ok I can confirm that the text pasting issue was due to middle-clicking, and the drag and drop issue was a bug in my file explorer. I can't understate how silly I feel lol. My first week of Linux has been sub-optimal.

For the drag and drop error, if the file you are dragging crossed over another UI element on the way out of the window, it won't let you drag it to other apps, so I had to drag it between two icons to make it work. Explains why I couldn't consistently replicate it.

[Screencast from 2024-10-12 15-01-01.webm](https://github.com/user-attachments/assets/e3ba34b3-cb29-40aa-b401-353df570daa3)

Thanks for all the help, and sorry for wasting your time, lol.

I still plan on adding alternate CSV delimiter support, though.

**Comment by AyushAgrawal-A2** [comment]
@paulwrath1223 
Thanks for confirming.
I will prevent the default middle click paste on Ubuntu. Meanwhile you can press and hold spacebar and drag to pan the canvas.
In Ubuntu 24.04, there is a bug currently where after waking from sleep, UI elements become weird and do not respond well with mouse events. Not sure if this is the scenario for you. I have to restart everytime, sleep is useless for me.

> I still plan on adding alternate CSV delimiter support, though.
Thanks for offering to do this, I am not sure currently whether we want to do this in UI like google sheets and let the user select the delimiter or do it automatically in rust.
I will bring this us in the next team meeting and open an issue tracking this. You may take a shot at it if you are still up for it, or I can finish this sometime this week.
