### ISSUE TITLE
Long text output from code bleeds and removes gridlines 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1995]
See image, issue difficult to describe 

![CleanShot 2024-10-29 at 09 43 03@2x](https://github.com/user-attachments/assets/34b09b23-e9a6-49a3-8cd7-3a8ff434c358)

**Comment by AyushAgrawal-A2** [comment]
@luke-quadratic 
not actionable, need more context

**Comment by AyushAgrawal-A2** [comment]
@luke-quadratic 
this should be fixed now, please confirm

**Comment by luke-quadratic** [comment]
Nice one - checked and is fixed in both QA and Prod
