### ISSUE TITLE
Open multi-line formula editor button in wrong place

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#1999]
Should be anchored to the top right always, not centered

![CleanShot 2024-10-29 at 10 32 13@2x](https://github.com/user-attachments/assets/bb4cce68-d056-48bd-bb8e-9ea66f75d425)

**Comment by AyushAgrawal-A2** [comment]
being redesigned / fixed in https://github.com/quadratichq/quadratic/pull/1972
