### ISSUE TITLE
bug: dark mode issues

### ISSUE THREAD

**Issue by waveminded** [quadratichq/quadratic#2006]
- [ ] rename file - can't read in dark mode, has white background
- [ ] grid text - click into a cell in dark mode, text is also dark and can't read until clicking out of that particular cell

**Comment by waveminded** [comment]
<img width="1132" alt="381670837-43aa4cf8-4a15-4ed0-90b1-beb3b9b3c2d7" src="https://github.com/user-attachments/assets/808289cb-eca3-40fa-8b42-7ef3e3b98bf0">

**Comment by waveminded** [comment]
**disappearing text**

![2024-10-30 16 54 26](https://github.com/user-attachments/assets/57b0c065-0e71-43a2-9330-0e9f4f990991)

**Comment by jimniels** [comment]
Data validations UI is broken (back arrow invisible)

![CleanShot 2024-10-30 at 22 03 33@2x](https://github.com/user-attachments/assets/f6853e3e-8a3d-400e-ab9c-d8315cdab9f5)

**Comment by AyushAgrawal-A2** [comment]
> Data validations UI is broken (back arrow invisible)

fixed in https://github.com/quadratichq/quadratic/pull/1864

**Comment by AyushAgrawal-A2** [comment]
>>Data validations UI is broken (back arrow invisible)
>
>fixed in https://github.com/quadratichq/quadratic/pull/1864

added fix to https://github.com/quadratichq/quadratic/pull/2053

**Comment by davidkircos** [comment]
Fixes look good to me! 

The only issue I notice is that when loading there is a grey bar on the top in dark mode. Screen flashes to white too, not sure if we can do anything about that.
![CleanShot 2024-11-08 at 11 57 59](https://github.com/user-attachments/assets/39a751c6-4f7e-47bf-a62f-9abf15c066bd)

**Comment by AyushAgrawal-A2** [comment]
>The only issue I notice is that when loading there is a grey bar on the top in dark mode. 

@davidkircos 
done
