### ISSUE TITLE
Long-term usage of Quadratic always results in slow-down followed by reload prompts 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#2016]
As title describes, long-term usage of the product always results in a slow-down and reload prompts. 

(happens regardless of size - e.g. was recently in sheet with 60 text cells where eventually it grind to a halt)

[placeholder for console etc]

**Comment by AyushAgrawal-A2** [comment]
should be better in https://github.com/quadratichq/quadratic/pull/1864 , needs long duration testing for confirmation

**Comment by taotien** [comment]
for me it's not long term, mine slows down within a few minutes, on a sheet with only a handful of cells and row of python generated dates

**Comment by AyushAgrawal-A2** [comment]
@taotien 
I have not noticed an app slow down this aggressive before, it will help alot if you can try our preview branch of PR https://github.com/quadratichq/quadratic/pull/1864 available on this link https://quadratic-git-ayush-aipanel.vercel.quadratic-preview.com/

Happy to ship just the fix on priority if you can confirm better performance on the preview link.
Also you can try out new AI features in that branch. Feedback is most welcome.

**Comment by taotien** [comment]
I think that did the trick, thanks!
