### ISSUE TITLE
Marketing Website: Broken link

### ISSUE THREAD

**Issue by sensingturtle** [quadratichq/quadratic#2039]
On [this page](https://www.quadratichq.com/blog/2024-08-09-sql-data-connections-in-spreadsheets), at the very end of the blog post, the link with text ‘**_read the SQL docs_**’ is broken.

<img width="813" alt="Screenshot 2024-11-07 at 12 56 15 PM" src="https://github.com/user-attachments/assets/ad22d87b-451a-4d7a-bf27-b09b6154cef1">

**Comment by luke-quadratic** [comment]
Fixed link, nice find!
