### ISSUE TITLE
Marketing Website: Typo in a code snippet

### ISSUE THREAD

**Issue by sensingturtle** [quadratichq/quadratic#2042]
The highlighted values (see image below) in the ‘Advanced’ tab on https://www.quadratichq.com/quadratic-101#read-data should be `0,8` instead of `0,100`

<img width="1225" alt="Screenshot 2024-11-07 at 5 09 07 PM" src="https://github.com/user-attachments/assets/17734efa-9fd7-4d7a-931f-fdba93564333">

**Comment by luke-quadratic** [comment]
Nice find, fixed.
