### ISSUE TITLE
Marketing Website: Return value in code snippet does not match corresponding spreadsheet

### ISSUE THREAD

**Issue by sensingturtle** [quadratichq/quadratic#2044]
The highlighted text (see image below) in the ‘Advanced’ tab’s Python code on https://www.quadratichq.com/quadratic-101#formulas does not match the text inside cell (1,1).

<img width="1179" alt="Screenshot 2024-11-07 at 5 42 32 PM" src="https://github.com/user-attachments/assets/7fba2bfa-13ee-469a-9138-6aa70a321c42">

Either the return value in the code snippet should be modified to `Invalid data` or the text inside cell (1,1) should be changed to `Invalid data (must be >5)`.

In the latter scenario, it would make sense to extend the width of column 1 like this –

<img width="513" alt="Screenshot 2024-11-07 at 5 48 08 PM" src="https://github.com/user-attachments/assets/a7123d4c-f712-4ed3-8e30-81b4631d0953">

**Comment by luke-quadratic** [comment]
Yet another nice find, fixed.
