### ISSUE TITLE
deleting a cell/cells does not update the dependency graph.

### ISSUE THREAD

**Issue by heizusan** [quadratichq/quadratic#206]
Verified by breakpoint and watching dgraph/qdb inside GetDGraphDB:

1) Edit a new cell to add python reference to other cells. dgraph edgeCount reflects the old dependency count (because it has not yet been modified).
2) Edit the cell to add or remove cell references. dgraph edgeCount reflects the correct count from the first edit (again, stale data)
3) Delete the cell.. dgraph edgeCount reflects the count from [2] (stale data).
4) Perform any operation that needs to get/update dgraph. dgraph edgeCount reflects [2] - NOT [3].

This is an issue in terms of a performance leak - and potentially invalid data.
  1) These stale/invalid dependency edges are a memory leak (albeit a small one).
  2) If one of the cells "referenced" in those edges is updated, it will push cells onto the update queue that do not need to be updated. Mostly this is a quick loop of no-ops on those cells - a small performance hit. However:
  3) If those cells have any non-deterministic/live computations (e.g. Random, or Date.now()), they will incorrectly be computed and updated with new values.

**Comment by davidkircos** [comment]
I believe this issue has been fixed in the `development` branch, which is
significantly ahead of `main`.

We hope to merge development this month.

David

**Comment by heizusan** [comment]
You're right. I was looking through the wrong branch this entire time...
