### ISSUE TITLE
bug: pasted link displays weird in cell

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#2072]
In this file

https://app.quadratichq.com/file/5a2ee1de-6c95-4cc7-af6a-755b94746667

When I paste a link in a particular cell, it displays strangely (almost like it's centered in the cell?)

When I paste it in the cell to the right, it displays as expected. However any cell to the left of that and its positioning is all messed up.

https://github.com/user-attachments/assets/5803302d-d370-4e07-9696-23f93abfbe06

**Comment by davidfig** [comment]
The align was center to center in those cells. I fixed it.

**Comment by jimniels** [comment]
That's weird — I reset the alignment on those and it was still doing it. Guess I was doing something wrong. Will close.
