### ISSUE TITLE
Top toolbar scrolls when hovering and scrolling with mouse

### ISSUE THREAD

**Issue by HactarCE** [quadratichq/quadratic#2082]
1. Open a file
2. Hover over the top toolbar (e.g., the "bold" button)
3. Scroll up/down with mouse

Expected behavior: nothing happens

Actual behavior: the toolbar scrolls a little bit

https://github.com/user-attachments/assets/1be38b62-f812-43b9-b882-98e677d56c14

**Comment by jimniels** [comment]
Fixed in #2004

**Comment by luke-quadratic** [comment]
Closed as completed and in prod via #2004
