### ISSUE TITLE
Minor grammatical error on the new AI landing page

### ISSUE THREAD

**Issue by sensingturtle** [quadratichq/quadratic#2091]
On https://www.quadratichq.com/ai , the highlighted text (see image below) in the section called ‘Analyze data fast’ should be –

> _insights **at** the speed of thought._

instead of

> _insights in the speed of thought._

![Screenshot 2024-11-20 at 5 04 57 PM](https://github.com/user-attachments/assets/9d47a99f-e71f-4183-84a4-cff1a68ecd3f)

**Comment by luke-quadratic** [comment]
you're a legend, nice find @sensingturtle 

will fix

**Comment by luke-quadratic** [comment]
fixed, ty for opening this issue!
