### ISSUE TITLE
bug: javascript network requests fail in a loop

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#2098]
It seems the proxy headers are duplicating on consecutive calls unless you're defining them inside the loop itself.

## This doesn't work

Code, where the `options` is defined at the top level of the function, then called inside a loop

![CleanShot 2024-11-22 at 14 33 37@2x](https://github.com/user-attachments/assets/51ee78ae-e2d4-4f9b-a892-005c7a1273a4)

Request headers for the 1st time `fetch` runs:

![CleanShot 2024-11-22 at 14 34 24@2x](https://github.com/user-attachments/assets/a52623c0-78c3-4fec-8e22-17c20feaa348)

Request headers for the 2nd time `fetch` runs in the loop:

![CleanShot 2024-11-22 at 14 34 58@2x](https://github.com/user-attachments/assets/ea86c892-33fa-4b7f-9147-c619bf368a75)

The 1st call succeeds. The 2nd call fails with a 401 Unauthorized error.

## This does work

Putting the options definition right alongside the `fetch` call

![CleanShot 2024-11-22 at 14 36 06@2x](https://github.com/user-attachments/assets/564f1be1-4e79-4cbd-ae17-0ec2f2cca7b0)

This makes both the 1st and 2nd requests work.

**Comment by ddimaria** [comment]
@AyushAgrawal-A2 from watching Jim go through this, the headers are sticky, so they get re-applied for each additional fetch call.
