### ISSUE TITLE
feat: Data Types

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#22]
- [ ] Have grid cells format text for common data types: currency, date, number, etc
- [ ] In Python take cells input and interpret them natively in their Quadratic Cell type. Ex if a user inputs a date, when the cell data arrives in python, it should be a DateTime type.

**Comment by jimniels** [comment]
Example where I had to use `int` to get the result i wanted:

I was trying to take a range of cells and multiply each value by 10, but as you can see, i wasn't expecting `11*10` to be `1111111111`

![image](https://github.com/quadratichq/quadratic/assets/1316441/a1fd0038-bcee-48f8-b2fe-5e9a642d0ce6)

Once i wrapped the cell value in int then it worked as expected:

![image](https://github.com/quadratichq/quadratic/assets/1316441/669ecda9-5323-446d-bcd3-a71b37705efa)

**Comment by jimniels** [comment]
Here's an example where I wanted to work with the value of a cell as a string, but had to convert it using `str()` first

<img width="929" alt="CleanShot 2023-05-11 at 16 44 50@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/8fa65c25-94ff-458c-bb00-9db87dc31d6d">

Once I wrap what `cell` returns, e.g. `str(cell(x, y))` then I can run `.split()`

<img width="933" alt="CleanShot 2023-05-11 at 16 45 04@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/83670b1a-870a-4dc8-ada6-68050bdf5ad4">

**Comment by jimniels** [comment]
[From the discord](https://discord.com/channels/1021488427977416714/1109582323575439400/1109943455238586388):

> Another small developer experience suggestion, right now cell(x, y) return an object, which forces me to wrap each cell in a str call. Maybe there's a way to add an alternative method that returns it as a str or int directly?

**Comment by davidkircos** [comment]
will be supported starting in `next`
