### ISSUE TITLE
Indicate active formatting state

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#220]
Similar to Notion, it would be a nice-to-have to indicate the current state in the formatting toolbar:

<img width="656" alt="CleanShot 2023-02-06 at 13 54 48@2x" src="https://user-images.githubusercontent.com/1316441/217083471-ce2af904-d83a-4be2-bd09-a8ff43739ac5.png">

Example:

<img width="1049" alt="CleanShot 2023-02-06 at 13 58 23@2x" src="https://user-images.githubusercontent.com/1316441/217084103-091af782-78ae-4e38-9dbb-65f315aca6cd.png">

But we also need to holistically consider all the places where we allow formatting and whether we want to communicate state (on/off/indeterminate) there too.

There's the formatting in the toolbar:

<img width="266" alt="CleanShot 2023-02-07 at 10 49 20@2x" src="https://user-images.githubusercontent.com/1316441/217324741-9813c0ff-b604-4691-adb8-c1f0cd5f8e23.png">

As well as in the command palette:

<img width="555" alt="CleanShot 2023-02-07 at 10 49 37@2x" src="https://user-images.githubusercontent.com/1316441/217324782-b727b160-6fb3-4a08-9b31-e70da273de1c.png">

**Comment by davidkircos** [comment]
very low priority
