### ISSUE TITLE
Starting a new grid and inputting data doesn't render anything

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#246]
If you start a new grid and start typing cell input, the input disappears when the cursor moves.

![Feb-10-2023 13-38-32](https://user-images.githubusercontent.com/1316441/218193129-d46364fb-5405-403f-a879-2b44ebf645d1.gif)

Must be a rendering issue because if you input some info and then refresh the page, the data then shows up on the grid.

**Comment by davidkircos** [comment]
I am not sure exactly when, but this issue has been fixed.
