### ISSUE TITLE
Ctrl+P to open Search doesn't work on Windows

### ISSUE THREAD

**Issue by HactarCE** [quadratichq/quadratic#249]
This issue occurs in both Chrome and Firefox.

[This SO link](https://stackoverflow.com/questions/18843936/how-to-disable-the-ctrlp-using-javascript-or-jquery) might be helpful

**Comment by davidkircos** [comment]
@jimniels does Figma use Command + P on windows?

**Comment by jimniels** [comment]
They actually support two different key combos. This is from [Figma's "Quick Actions" docs](https://help.figma.com/hc/en-us/articles/360040328653-Use-shortcuts-and-quick-actions):

<img width="505" alt="Screenshot 2023-02-10 at 4 25 24 PM" src="https://user-images.githubusercontent.com/1316441/218221078-94a22a8f-9364-4911-97b8-ffe358cee6d5.png">

But yes, it's `Ctrl + P` on Windows.

Not sure why this isn't working...I don't have a windows machine to test on, but [the code](https://github.com/quadratichq/quadratic/blob/development/src/core/gridGL/interaction/keyboard/keyboardViewport.ts#L32) _looks_ like it should work?

**Comment by HactarCE** [comment]
Ah I left out the crucial detail that it opens the browser's "print" dialog

**Comment by jimniels** [comment]
@HactarCE is this still an issue (i know we did some work that remapped shortcuts to use `.key` I wonder if this bug disappeared...?

**Comment by HactarCE** [comment]
Nope! This is working now
