### ISSUE TITLE
bug: Rendering Overflow Text

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#278]
<img width="1709" alt="Screenshot 2023-02-16 at 12 06 48 PM" src="https://user-images.githubusercontent.com/3479421/219463261-f3d7b8f0-9862-41eb-8748-5dff8592c9bd.png">

**Comment by davidfig** [comment]
I still can't replicate this bug. I expect it has something to do with texture size for quadrants (maybe width or height === 0?). Let me know if you see it in a certain file. python.grid doesn't trigger it on my machine.
