### ISSUE TITLE
bug: paste doesn't doesn't work in safari/firefox

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#301]
In Safari/Firefox, you can cut/copy within Quadratic but when you try to paste nothing happens (nothing in the console).

You can tell it is cutting (you see it disappear) and copying because when you cut/copy, the content ends up on your computer’s clipboard. But when you try to paste, nothing happens.

![copy-paste](https://user-images.githubusercontent.com/1316441/220456128-c45cdf58-bbb5-4ec3-a180-934da94d358e.gif)

**Comment by davidkircos** [comment]
This is also an issue in Microsoft Edge

**Comment by jimniels** [comment]
Cut/paste works in safari now, but it doesn't preserve formatting

![May-17-2023 13-35-01](https://github.com/quadratichq/quadratic/assets/1316441/9e141114-1e34-4e6d-aa90-d463b1588c7f)

We might want to create a high-level ticket to track feature parity across browsers, e.g. "these are features which work in chrome but not yet in other browsers (fully): 1), 2), 3)"
