### ISSUE TITLE
File Issues

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#303]
- [x] #189
- [ ] Add a way to open a file from the internet `https://app.quadratichq.com/?load_file=https://fileserver.com/file.grid`

**Comment by jimniels** [comment]
This was done in the files work — and completed fully through the auth process with https://github.com/quadratichq/quadratic/pull/412

You can now open any (valid) Quadratic file from the internet by appending the `file` query param with a URL, e.g:

`?file=https://example.com/path/to/my-file.grid`
