### ISSUE TITLE
feat: CSV Upload / Export

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#305]
Add the ability to upload a CSV and Export a CSV from Quadratic.

Exporting a CSV should work on a region of cells, and give you a file.

**Comment by evanwolf** [comment]
I've been having difficulty importing .csv files (about 7k rows by 5 columns) generated by excel. any thoughts on ways to debug this? tried in chrome and firefox. either got an infinite time or a "file type not recognized".

and... is this the right place to have this conversation.

**Comment by davidkircos** [comment]
> I've been having difficulty importing .csv files (about 7k rows by 5 columns) generated by excel. any thoughts on ways to debug this? tried in chrome and firefox. either got an infinite time or a "file type not recognized".
> 
> 
> 
> and... is this the right place to have this conversation. 

Hey Evan. Are you willing to share the file? I can help you debug this issue. Can also send privately to david@QuadraticHQ.com
