### ISSUE TITLE
bug: Overflow Quadrant Bug

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#306]
When an overflow Quadrant is cleared via an array formula, it is not properly re rendered.

Example: 
![Feb-21-2023 21-52-04](https://user-images.githubusercontent.com/3479421/220525250-59ef9f05-304d-4e10-9b0d-ab0a2fe3e82b.gif)

Steps to Reproduce:
1. Create an array output with overflow quadrants
2. Shorten the array output where some cells are deleted.
3. This leaves a phantom overflow Quadrant

**Comment by jimniels** [comment]
I believe this is fixed, can you confirm @davidfig @davidkircos

**Comment by davidfig** [comment]
Can confirm this is fixed
