### ISSUE TITLE
bug: select all, clear format doesn't work

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#313]
Steps to reproduce:

- Open the monte carlo sample file
- CMD + A to select all
- Clear formatting in toolbar

Note that only some formatting is removed

https://user-images.githubusercontent.com/1316441/221290464-50109309-98a8-40b9-b8e0-2e4004bfb93a.mp4

**Comment by davidkircos** [comment]
repeat of https://github.com/quadratichq/quadratic/issues/298
