### ISSUE TITLE
feat: Importing additional python libraries

### ISSUE THREAD

**Issue by N-Demir** [quadratichq/quadratic#324]
Hey there! Will it be possible to install additional python libraries in some way? For example by providing a `requirements.txt` file or giving a list of them in a column or whatever form factor makes sense. Often some script I'm looking to write would benefit from taking advantage of some library. Say `openai`, for example, because I wanted to do some sales automation using quadratic and GPT.

**Comment by N-Demir** [comment]
Fwiw, maybe there's something interesting here for quadratic? https://www.pythonanywhere.com/

**Comment by luke-quadratic** [comment]
closing, creating new related issue to add to roadmap with spec for how this would work
