### ISSUE TITLE
feat: support text size resizing in code editor

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#325]
When you're focused on the code editor today, hitting `CMD` + `+` or `CMD` + `-` zooms the grid, not the text size of the font in the code editor. 

Should probably allow folks to bump up the font size to a size that fits their needs.

**Comment by luke-quadratic** [comment]
Should we make this more obvious? I forget 100% of the time how to perform this action.

**Comment by jimniels** [comment]
The hotkeys for this `CMD +` and `CMD -` were implemented in #1096
