### ISSUE TITLE
Database Support

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#35]
[Knex.js for connecting databases](http://knexjs.org/)

Should work for npm start & electron. No support for "Cloud".

- [ ] get node+express running alongside app (web + electron)
- [ ] store database credentials in `localstorage`
- [ ] pipe requests through Node, Express API running locally
- [ ] Database credentatls are added via file bar
- [ ] Databaes are queried via cells.
- [ ] Create SQL Editor
- [ ] Select target database, or grid

**Comment by mingfang** [comment]
FYI - this is a combination of postgres client for the browser and websocket proxy on the server, to enable running postgres sql over the web. 
https://github.com/neondatabase/serverless

**Comment by davidkircos** [comment]
@mingfang That is really cool. It seems to me the better approach is to proxy database requests, which would support a much wider range of databases and keep the client application smaller.

**Comment by mingfang** [comment]
@davidkircos Yes I agree that's a better approach.
There's a low-code platform called Openblocks that has this approach.
https://docs.openblocks.dev/queries/query-basics

Ideally(for me) is to integrate Quadratic with Openblocks.
But that requires Quadratic to be a standalone React component.

**Comment by davidkircos** [comment]
Makes sense.

What do you use OpenBlocks for? We are working towards being able to import data from SQL, run code, and generate output such as charts and graphs directly in Quadratic. If we had that would it be feasible to work solely inside of Quadratic?

**Comment by mingfang** [comment]
All of that is already done in Openblocks.
I guess it's a choice of putting "openblocks" into Quadratic vs putting Quadratic(React grid) into Openblocks.
Both are great.
