### ISSUE TITLE
bug: Turning Off Cell Types Can Unload File

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#355]
![Mar-14-2023 11-26-09](https://user-images.githubusercontent.com/3479421/225088164-220701e1-2b7e-4df7-a6c5-1af109d80fdb.gif)

**Comment by davidfig** [comment]
This may be a more general bug with the way file loading works in this branch. I think until you change the sheet, it can revert to an old file.

**Comment by davidkircos** [comment]
@davidfig Could you explain what you mean? I did change the sheet, and then it reverted to an old file after.

**Comment by davidfig** [comment]
Then it's a different bug. I've noticed some strange behavior with the old file loading. Check if this happens in the new loader branch.

**Comment by davidkircos** [comment]
Yeah, good point. I can't reproduce the bug in this branch #308
