### ISSUE TITLE
feat: drag a `.grid` file to import it

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#397]
Similar to how dragging a CSV file will drop it's data on to the grid, dragging a `.grid` file will save the current file on the grid and import the one that the user just dragged (if it's a valid file, otherwise show some kind of error noting what happened).

**Comment by davidkircos** [comment]
We may want to add a dialogue that confirms this is what they user wants to
do. Because it does deviate from how a CSV is just get imported into the
current sheet
