### ISSUE TITLE
feat: Quadratic Hosted CORS proxy & improved Python API requests overall

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#401]
Create a cors proxy and Python Lib to access it that mimics 'requests'. 

This will make it much easier to fetch data

- [ ] Secrets added at proxy level?

**Comment by lucasew** [comment]
Well, CORS has a reason to exist.

That would allow some abuses, and bandwidth for arbitrary data is not so cacheable and cheap to host.

Here is an alternative:
https://github.com/Rob--W/cors-anywhere

**Comment by davidkircos** [comment]
Nice, thanks for sharing cors-anywhere.

We will add user auth and rate limiting on the CORs proxy to combat abuse.

**Comment by davidkircos** [comment]
https://github.com/koenvo/pyodide-http

We can also document this in the meantime and maybe install it by default

**Comment by ddimaria** [comment]
We now load pyodide-http by default.  Is there more work to do on this @luke-quadratic @davidkircos?
