### ISSUE TITLE
feat: use File System Access API to save stuff without a login

### ISSUE THREAD

**Issue by lucasew** [quadratichq/quadratic#404]
[File System Access API is a browser API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) that is kinda new but already [supported in Chrome](https://caniuse.com/native-filesystem-api), for example, that allows the browser to ask permission to write directly to files in the user's computer.

Those grid files it generates are basically JSON files. I can see a bottleneck if the spreadsheet is too big, though, but for a quick onboard it can be really useful and demonstrate that there is no lock-in because the file is just a JSON.

Another possibility is to use other quick scripts to generate spreadsheets automatically later, a thing that is much simpler than with Excel because the data format has much better tooling support.

**Comment by davidkircos** [comment]
We are working on Quadratic as a desktop app via Electron. As a native app it would be great to use the file browser API to allow users to easily work on files locally on their filesystem. 

We have plans to move away from JSON files in the long term and store data sets in Apache Arrow and code in a flat format that git can support.

**Comment by davidkircos** [comment]
Quadratic is a cloud app and has no immediate plans to support this.
