### ISSUE TITLE
bug: broken file due to invalid array_output schema

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#415]
[Per a comment in the discord](https://discord.com/channels/1021488427977416714/1021488428614942792/1094112529036349520), a user created a file and couldn't re-open it the next day.

I got a hold of the file and after importing it locally and having it run the file schema validation, i found the error was coming from this part of the file:

![image](https://user-images.githubusercontent.com/1316441/230703452-e7b2f34e-d5d6-4728-8b94-de1c8d5746bb.png)

`array_output` is not supposed to allow objects inside of it, so zod was throwing an error when trying to parse and validate it before the app opened it.

![image](https://user-images.githubusercontent.com/1316441/230703474-5c17820f-7a01-4eb9-adde-6b59b86e5387.png)

So i just removed those two empty objects and imported it back into the app and it worked, and i saw this in the spreadsheet

![image](https://user-images.githubusercontent.com/1316441/230703484-1b8ce9bd-e2ce-426b-9c77-fe3339ee871b.png)

**Comment by jimniels** [comment]
Original file (renamed from `.grid` to `.txt`):

[Build_PC.txt](https://github.com/quadratichq/quadratic/files/11182538/Build_PC.txt)

**Comment by davidkircos** [comment]
Yeah, this is a repeatable issue. Should be an easy enough fix

**Comment by jimniels** [comment]
This is a problem for nested arrays too

![image](https://github.com/quadratichq/quadratic/assets/1316441/3a7cc70d-ba19-4cfd-a017-7ebab4ac05a3)
