### ISSUE TITLE
Any plans for a docker based deployment guide for self-hosting?

### ISSUE THREAD

**Issue by ovizii** [quadratichq/quadratic#416]
Nice project you have here!
The title says it all :-)

**Comment by davidkircos** [comment]
Someone did a PR last week https://github.com/quadratichq/quadratic/pull/395

What are the benefits of adding a dockerfile / what would you want it to be able to do?

**Comment by ovizii** [comment]
Thanks for pointing me that way. A Dockerfile is just the first step, the next step would be an automated image build. :-) 

The reason I am asking for a docker based deployment is that this way I could just run the container with one line, something along the lines of:

`docker run -p 1234:80 -v /local/data/folder:/mountpoint/inside/container --restart always quadratiqhq:latest`

No more manual installing and updating along these lines.

```
Run Quadratic Locally
Install npm, rustup, and wasm-pack
Run rustup target add wasm32-unknown-unknown
Build the Rust/WASM npm run build:wasm
run npm install
Run Web npm start

Run Electron npm run dev
```

You're basically asking about the benefits of Docker. In short, I'd say: I can test any app I like with a few commands and I can just remove everything with one command without having to install anything on the host except docker. 
Benefits like: portable, scalable, lightweight, isolation come to mind.

**Comment by timovdw** [comment]
The dockerfile in #395 fails on a Macbook M1 docker platform.

```
67.41 Error: no prebuilt wasm-opt binaries are available for this platform: Unrecognized target!
67.41 To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
```

Sadly I am not a rust expert so don't know how to debug this.

**Comment by hasnat** [comment]
@timovdw you can try `docker build -t quadratic --platform=linux/amd64 .` QEMU it, or possibly `linux/arm/v6` ?

**Comment by timovdw** [comment]
> @timovdw you can try `docker build -t quadratic --platform=linux/amd64 .` QEMU it, or possibly `linux/arm/v6` ?

I confirm this works indeed, thank you.

Takes around 700 seconds to build on a M1 max

Then it runs using this command
`docker run --platform linux/amd64 -p 3000:3000 quadratic`

Startup is quite slow, around 90 seconds

**Comment by davidkircos** [comment]
we are planning on hosting Quadratic in the cloud. we don't currently plan to offer an self hosted option

**Comment by ovizii** [comment]
> we are planning on hosting Quadratic in the cloud. we don't currently plan to offer an self hosted option

Hi there, let me ask a last question seeing that the ticket has been closed: 
was this all a misunderstanding or did you simply change your plans for Quadratic?

**Comment by davidkircos** [comment]
We are working on a self-hosted option via docker.

If you are interested please contact us: https://www.quadratichq.com/contact

**Comment by davidkircos** [comment]
We are working on a self-hosted option via docker.

If you are interested please contact us: https://www.quadratichq.com/contact
