### ISSUE TITLE
SciPy package and modules not importing

### ISSUE THREAD

**Issue by robdongas** [quadratichq/quadratic#419]
### Issue description
Unable to import the `stats` module from the `scipy` package.

### Steps to reproduce the issue

1. Create a new cell with python code
2. Import `micropip` and `scipy`
```python
import micropip
await micropip.install("scipy")
```
3. Import the stats module
```python
import scipy.stats as stats
```
### What's the expected result?
Module is imported and can be used for statistics.

### What's the actual result?

Importing the `scipy` package from `micropip`:
```
ERROR: JsException on line 201: Error: bad export type for `cdotu_`: undefined
```
This error only appears the first time when installing from `micropip`.

Importing the `stats` module:
```
ERROR: SystemError on line 213: initialization of _fblas raised unreported exception
```

### Additional details / screenshots

Trying to import scipy normally (without `micropip`) doesn't appear to work, even though the docs say it is an included package:
```python
import scipy as sp
```
returns:
```
ERROR: ModuleNotFoundError on line 1: No module named 'scipy'
```

**Comment by davidkircos** [comment]
Quadratic runs Python code in Pyodide. It looks like some modules in scipy don't work correctly with Pyodide. See this Issue on their repo https://github.com/pyodide/pyodide/issues/2727#issuecomment-1157866792

We have plans to enable users to run Python in a Linux container which should have much better package support. However, for now, this is something we can't fix until Pyodide improves its support for Scipy.

**Comment by robdongas** [comment]
Ah that's a shame, thanks for looking into it.

**Comment by lesteve** [comment]
@davidkircos I am not familiar with [QuadraticHQ.com](https://quadratichq.com/) and how it uses Pyodide but inside Pyodide, `import scipy` or `import scipy.stats` works fine so I feel like the blame is not fully on Pyodide on this one.

You can try it yourself in the latest Pyodide version:
https://pyodide.org/en/stable/console.html

**Comment by davidkircos** [comment]
Good point. Maybe we just need to upgrade Pyodide in Quadratic
