### ISSUE TITLE
Keyboard shortcuts should use `key` rather than `code`

### ISSUE THREAD

**Issue by HactarCE** [quadratichq/quadratic#426]
Users of non-QWERTY keyboard layouts expect keybinds such as <kbd>Ctrl</kbd>+<kbd>Z</kbd> and <kbd>Ctrl</kbd>+<kbd>O</kbd> to be based the symbol produced by the key rather than physical key. For example, I press the key labeled <kbd>;</kbd> to produce the letter <kbd>O</kbd>, so I expect the "Open" command to be bound to <kbd>Ctrl</kbd>+that key.

Sidenote: this is why I thought that <kbd>Ctrl</kbd>+<kbd>O</kbd> wasn't being overridden correctly.

**Comment by jimniels** [comment]
THis should be fixed for current shortcuts in the app when we merge https://github.com/quadratichq/quadratic/pull/434#pullrequestreview-1398751126

**Comment by jimniels** [comment]
This was fixed in #434
