### ISSUE TITLE
foreign languages' special characters disappear when not editing the cell.

### ISSUE THREAD

**Issue by bricout-thomas** [quadratichq/quadratic#448]
I have tried french ( é, ù, è, ç, etc ). Japanese hiragana and katakana ( おれが, パン ), kanji/hanzi ( 食 ), german umlauts, and there's probably more.

They appear temporarily when editing the cell but disappear when quitting editing, They are still there however and reappear if the cell is reedited.

**Comment by davidkircos** [comment]
Hey @bricout-thomas thanks for creating this issue.

This is because the Quadratic grid id rendered using WebGL. We currently only support the font Open Sans and a small char sheet with it. We are working to improve language support in the future.

**Comment by jimniels** [comment]
There are two issues going on here:

1. The cell input allows the user to type any character, as it's a native browser input. However, once you hit 'Enter' and save the value to the sheet, some of those characters may visually disappear (even though they are saved as part of the cell's value). We should address this as part of #478 
2. The sheet is rendered with webGL and can't display many characters outside of English / Open Sans (per [David's comment](https://github.com/quadratichq/quadratic/issues/448#issuecomment-1526523961)). This will be addressed via #506

Given that these issues are addressed elsewhere, I'm going to close this issue and you can follow the progress of this work on the issues referenced above.
