### ISSUE TITLE
feature: customizable paneling within the app

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#449]
Like how Zed just lets you drag panels around wherever you want, would be neat if Quadratic let you put things wherever you need them given your current working context.

![Apr-28-2023 10-20-36](https://user-images.githubusercontent.com/1316441/235201936-61a2e6db-860f-4d76-9a95-84e26f0e29bf.gif)

For example: in Zed I can easily create a view with 4 panels by just dragging them around:

<img width="1548" alt="CleanShot 2023-04-28 at 10 16 21@2x" src="https://user-images.githubusercontent.com/1316441/235201996-f3b4e9d4-92da-4f3d-b296-75455aaa8388.png">

**Comment by luke-quadratic** [comment]
Did a lot of this via recent paneling work #1334 , reopen if more paneling work becomes a prio in the future
