### ISSUE TITLE
feat: handle unsaved changes

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#468]
If you have the code editor open with unsaved changes, and you go to create a new file, it will discard your unsaved changes in the editor without prompting you whether you want to save & run them or not.

**Comment by jimniels** [comment]
It also discards changes when you have the code editor open and go to add python to another cell
![May-11-2023 12-47-17](https://github.com/quadratichq/quadratic/assets/1316441/848fdf3a-27d8-4cb1-b40b-92c82da50675)

**Comment by jimniels** [comment]
It seems like there could be a lot of cases in the app where you want to edit some code and the "are you sure you want to discard your unsaved changes?" will pop up again and again. It could become quite annoying.

I'm wondering if maybe we need to expand the idea of the editor to have "tabs" which correspond to cells on the grid, so you can have open multiple 'tabs' at once and then when you click a new cell to edit, it opens a new cell rather than closes the current one and prompts you if you want to save your changes. 

Example:

<img width="2000" alt="CleanShot 2023-05-11 at 13 15 43@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/ac7988d5-5539-4783-b232-f64c9590aa5b">

**Comment by davidkircos** [comment]
I like the concept of tabs. And panes. So you could move one to the bottom
or top or left side
