### ISSUE TITLE
feature: relative cell references

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#469]
Building off #269 (and related to #408), this is an issue specifically for supporting relative cell references. There are a couple different ideas here.

**Relative vs. absolute for when cells are moved**

For example, how excel lets you reference `A1` or `$A$1` and when you drag/move cells those references do or don't change.

**Relative vs. absolute for getting a cell's value**

For example, somebody might say: "I want the value that's 2 up and 3 over to the right from the current one".

As a purely illustrative example of one solution, we could allow the current `cell` function to accept an additional parameter that can specify the `x` and `y` to be _directional_ rather than absolute, e.g. `cell(2, 3, { 'x': 'up', 'y': 'right' })` means "from the current cell, grab the value of the cell that's 2 up and 3 to the right".

Or, as a contrasting solution example, perhaps this can be accomplished by providing a function that returns the `x` and `y` of the currently active cell. From there, you can grab the value of any cell you want relative to the current one. Again, as a purely illustrative example, the special function `current_cell` would return the `x` and `y` coordinates of the active cell

```python
# get the value of the current cell, e.g. (0,0)
current_x, current_y = current_cell()

# grab the value that's up 2 and over 3 to the right
value = cell(x - 2, y + 3)
```

This would be useful in for or while loops:

```python
# get the value of the current cell, e.g. (0,0)
current_x, current_y = current_cell()

# grab the value in cells going 10 rows down in this column
values = []
for i in 10
  values.push(cell(current_x + i, current_y))
  
# return value to grid
values
```

**Comment by jimniels** [comment]
Current `cell` syntax:

- `cell(x, y)` Returns value of cell at x,y coordinates

Spitballing on expanding the `cell` syntax:

- `cell()` 0 args: Returns named coordinates of current cell, e.g `{x, y}`
- `cell({ x,y })` 1 arg (obj): Returns value of specified cell (allows mixing ordering, e.g. `{ y: 2, x: 0 }`)
- `cell("name")` 1 arg (string): Returns value of named cell (must support named cells)
- `cell(1)` 1 arg (number): Returns value of specified cell at `x,y`, e.g. `1,1`
- `cell(x,y)` 2 args (number, number):  Returns value of named cell (backwards compatible)

**Comment by N-Demir** [comment]
+1! Having a function to get the current cell's position would be awesome!
