### ISSUE TITLE
fix: prevent circular references

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#471]
If somebody references the cell they're currently in, the app just gets stuck in an infinite loop with no way to exit except refresh the page

<img width="1740" alt="CleanShot 2023-05-05 at 08 49 21@2x" src="https://user-images.githubusercontent.com/1316441/236494704-f10f0d5c-72a9-402b-944d-66fd2ad94620.png">

![CleanShot 2023-05-05 at 08 49 39@2x](https://user-images.githubusercontent.com/1316441/236494718-ad4705fb-aa8b-4359-aa0e-eab14bf24ddd.png)

**Comment by davidkircos** [comment]
This is fixed in a individual cell, but you can still create a circular ref with two cells

**Comment by ddimaria** [comment]
I confirmed that individual cell reference are now caught.  I can cause the infinite loop by:

1. Code cell at (0,0) that reads from cell (1,0)
1. Code cell at (1,0) that reads from cell (0,0)

![Screenshot 2023-11-22 at 12 43 09 PM](https://github.com/quadratichq/quadratic/assets/1536436/c1d0dfbb-8852-47d8-ac5d-52a4964766e2)

I would expect at least the ability to cancel the execution, but would prefer to just generate an error in the code editor's console.

**Comment by luke-quadratic** [comment]
Can now cancel, marking to close pending discussion
