### ISSUE TITLE
bug: special characters show in cell edit but not the grid

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#478]
It looks like certain textual characters simply aren't allowed to render on the grid. For example, if you're editing a cell and type an emoji, it will appear _while you're editing the cell_ but then it will disappear once you save the change.

![May-08-2023 13-14-10](https://user-images.githubusercontent.com/1316441/236912394-ce2669df-7a8d-4294-8f38-153a672834e9.gif)

I imagine this is because the cell input is a DOM element but what's on the grid is rendered as an image (and we currently only support rendering a certain range of textual characters on the grid).

Feels like our options are:

1. Support a wider range of characters
2. Don't allow the text input to accept characters which we won't display

No. 1 is likely a longer-term goal, while no. 2 tries to address the slight weirdness that exists in today's implementation. It seems a little odd that you can _input_ a character, but it's hidden from you when you're looking at the spreadsheet.

Seems better IMO to not allow inputting characters we can't render, that way you don't get these magical characters that appear out of thin air when you go to edit a cell.

![May-08-2023 13-19-56](https://user-images.githubusercontent.com/1316441/236913422-47798ae1-ff0e-4588-b424-88c7fd46f4f3.gif)

**Comment by jimniels** [comment]
This issue is an example: https://github.com/quadratichq/quadratic/issues/448

Maybe we should disallow entering these characters entirely? Then people don't end up in a situation where they _see_ the value when they type it but then it disappears when they save it to the sheet.

**Comment by luke-quadratic** [comment]
duplicate
