### ISSUE TITLE
bug: cell input offscreen overrides column header

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#479]
If you have the cursor on a cell that is slightly offscreen:
<img width="130" alt="CleanShot 2023-05-09 at 10 57 30@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/6f116b59-8f5a-42c9-b2d9-60194dec937f">

And then you begin to edit that cell's contents, they appear _over_ the row headers:

<img width="126" alt="CleanShot 2023-05-09 at 10 57 36@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/0018b48d-1d64-4d2d-8c64-4642808656ed">

Not sure what the solution is here...I think I would expect that if I begin to edit a cell whose contents aren’t entirely on screen, the viewport would scroll just enough to bring it into view.

**Comment by davidfig** [comment]
Not sure how to fix this. If you start the edit, the app does move the entire cell into view. But if you move the viewport while editing, then you can get into the above state. I don't think we want to prohibit this behavior, however. <CellInput is over the canvas, so it would be difficult to clip the overlapping area. My suggestion is to leave this as is for now, and then if we ever move away from <CellInput to a pixi input solution then I can fix it.

**Comment by jimniels** [comment]
Ah ok, yeah that's great context. Gonna close for now as "won't fix"
