### ISSUE TITLE
⇧+`/` or ⌘+`/` to show an in-sheet help menu 

### ISSUE THREAD

**Issue by anthonycorletti** [quadratichq/quadratic#48]
while perusing http://early.quadratic.to I often forgot what I could do and would like to be able to bring up a help menu or search menu of all actions I could take that aren't just specific to cell operations (like `/` is used for). e.g. share, export, duplicate, archive the grid etc

**Comment by anthonycorletti** [comment]
for example with figma https://help.figma.com/hc/en-us/articles/360040328653-Use-shortcuts-and-quick-actions#Use_quick_actions

**Comment by jimniels** [comment]
You can now do this in Quadratic. We're still working on filling in the menu with all applicable actions, but you can open the command palette via the UI

![CleanShot 2023-03-28 at 15 01 31@2x](https://user-images.githubusercontent.com/1316441/228365925-2b74ad40-9c05-412d-b583-45e1dbaabcb6.png)

Or by its shortcut `CMD` + `P` or `CMD` + `/`

<img width="664" alt="CleanShot 2023-03-28 at 15 02 18@2x" src="https://user-images.githubusercontent.com/1316441/228366086-18e6d64c-6e7e-46f7-b325-9708f588438e.png">
