### ISSUE TITLE
bug: infinite loop runs on valid code near origin

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#485]
Given the following:

<img width="1474" alt="CleanShot 2023-05-10 at 23 21 52@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/8b2d1137-63e8-4acf-afba-ea900e08d94e">

Reading left-to-right, if you try to subtract the first column from the second column and stick it in the third, the code editor gets stuck in an infinite loop of processing

![May-10-2023 23-22-44](https://github.com/quadratichq/quadratic/assets/1316441/f548c789-c11a-40f9-8681-ac314a806ede)

Code:

```python
result = []
for i in range(3):
    cell1 = int(cell(-1, -1+i))
    cell2 = int(cell(0, -1+i))
    # Uncomment this line and get stuck in an infinite loop
    # result.append(cell1 - cell2)
result
```

Similarly, if you try to do the same thing, but with some slightly different code:

<img width="1473" alt="CleanShot 2023-05-10 at 23 25 29@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/db7bdd86-7140-444f-86c5-ea9b6cbf88cb">

You get the same result. Uncommenting that line of code makes the editor get stuck spinning.

Code:

```python
result = []
col1 = cells((-1,-1), (-1,1))
col1 = col1.applymap(int)
col2 = cells((0,-1), (0,1))
col2 = col2.applymap(int)
# Uncomment this line and get stuck in an infinite loop
# result = col1-col2
result
```

In either of those cases if you move the code so it runs in a cell not directly adjacent to the cells it's referencing, the code runs just fine without getting stuck spinning.

![CleanShot 2023-05-10 at 23 27 19@2x](https://github.com/quadratichq/quadratic/assets/1316441/233e14d0-4850-4da5-9aaf-f9692e75effb)

Test file (rename from `.txt` to `.grid`)

[Test Range Notation.txt](https://github.com/quadratichq/quadratic/files/11448434/Test.Range.Notation.txt)

**Comment by jimniels** [comment]
This is not working for the following code:

```
result = []
for i in range(3):
    cell1 = cell(-1, -1+i)
    cell2 = cell(0, -1+i)
    # Uncomment this line and get stuck in an infinite loop
    # result.append(cell1 - cell2)
result
```

**Comment by davidkircos** [comment]
Verified this bug still exsits

**Comment by davidfig** [comment]
This seems to be fixed in a-team. Please verify

**Comment by luke-quadratic** [comment]
confirming no longer an issue, closing
