### ISSUE TITLE
Closing tab doesn't confirm unsaved changes in code editor

### ISSUE THREAD

**Issue by HactarCE** [quadratichq/quadratic#486]

**Comment by jimniels** [comment]
Similar to the functionality of sites like [regex101](https://regex101.com/), when you have active, unsaved changes in the code editor and hit CMD + W or try to close the tab, we should used the browser's native dialog to interrupt the close and ask if you really want to discard your current changes.

<img width="488" alt="CleanShot 2023-05-17 at 10 47 18@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/e4b5ddb1-c046-4ae5-adf9-55525dd6d4b4">

<img width="446" alt="CleanShot 2023-05-17 at 10 49 09@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/50ecb5d4-dabb-4b59-a0cc-9ab32efae996">

<img width="332" alt="CleanShot 2023-05-17 at 10 49 25@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/7dd32d0c-a7c4-42b0-9549-a509355f4a95">
