### ISSUE TITLE
pandas.Series behaviour differs from a pandas.DataFrame

### ISSUE THREAD

**Issue by bartbroere** [quadratichq/quadratic#49]
My apologies if this issue was already tracked somewhere else, but when I make a `pandas.Series` in a cell, it looks different from when I make the same column in a `pandas.DataFrame`.

![image](https://user-images.githubusercontent.com/2715782/163557899-ac71f401-6696-426e-9120-39c4d3697fbf.png)

**Comment by davidkircos** [comment]
Yes, this is a bug. I believe it is simply rendered as a single cell multiline string.

Will fix.

**Comment by davidkircos** [comment]
<img width="1271" alt="Screen Shot 2022-05-10 at 3 26 48 PM" src="https://user-images.githubusercontent.com/3479421/167724718-160679ec-8561-4551-a5a1-1c45cd0673d6.png">

Fixed in #60
