### ISSUE TITLE
feature: Teams / collaboration

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#490]
This is a generic issue to capture everything that would fall under the category of "collaboration" (sharing, live multiplayer, etc.)

We know it's something people want. We're going to get to it. Upvote to show your support or comment with your feedback.

**Comment by davidkircos** [comment]
- [ ] - DataTypes
- [ ] - Sheets
- [ ] - Moving Cells
- [ ] - Add/ remove columns/rows
- [ ] -  Relative references
