### ISSUE TITLE
Integrating Python requests

### ISSUE THREAD

**Issue by bartbroere** [quadratichq/quadratic#50]
As discussed before with @davidkircos , it would be cool if `requests` could be integrated in Quadratic.

This in turn could enable all kinds of cool use cases, like loading CSV from an URL.

```python
import pandas
from io import StringIO
import requests

pandas.read_csv(StringIO(requests.get('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv').text))
```

My current progress of shimming `requests` is tracked here https://github.com/bartbroere/requests/pull/1 and here: https://github.com/NetherlandsForensicInstitute/pyodide/blob/0.19.0/packages/requests/meta.yaml

It is integrated in custom Pyodide builds by patching the original `requests` package. I would be happy to help and get this to work.

**Comment by luke-quadratic** [comment]
closing, duplicate of #401
