### ISSUE TITLE
Comma should maybe imply blank argument in formulas

### ISSUE THREAD

**Issue by HactarCE** [quadratichq/quadratic#514]
In Excel, `AVERAGE(1,2,3,)` evaluates to `1.5` because the last `,` implies a blank argument at the end, which coerces to zero.

# Is this something we want?

Pros:
- Excel-compatible
- Useful (albeit cursed) way to leave optional arguments blank in formulas

Cons:
- Unexpected behavior for anyone coming from a programming background
- Many people prefer trailing commas in multi-line function calls, which would have subtly different semantics

Alternatives:
- Can add something new like `_` to stand in for empty argument, and convert formulas when importing from Excel

# What would this look like?

Cases to test:
- [ ] `AVERAGE(1,2,3)` = 2
- [ ] `AVERAGE(1,2,3,0)` = 1.5
- [ ] `AVERAGE(1,2,3,)` = 1.5
- [ ] `AVERAGE(1,2,3,"")` results in an error
- [ ] `AVERAGE(1,2,3,A1)` = 2 (where `A1` is empty or contains an empty string)

Cases to test with arrays:
- [ ] `AVERAGE(1,2,3,{})` results in an error in Excel, but I think it's reasonable to return `2`
- [ ] `AVERAGE(1,2,3,{""})` = 2
- [ ] `AVERAGE(1,2,3,{0})` = 1.5

**Comment by luke-quadratic** [comment]
stale issue, feel free to reopen if deemed worthwhile
