### ISSUE TITLE
Column and row spans in formulas

### ISSUE THREAD

**Issue by HactarCE** [quadratichq/quadratic#515]
In Excel, `A:C` refers to a range of columns that spans the height of the whole sheet. We need to figure out the semantics of this in.

- Most Excel formulas only look at non-blank cells, so we can restrict the formula to any range that contains all the same non-blank cells
- An Excel formula like `COUNTBLANK(A:A)` counts _all_ cells in the column, even blank ones. E.g., `COUNTBLANK(A:A)` returns 2^20 and `COUNTBLANK(1:1)` returns 2^14.

To make this happen, we need:
- [ ] Function on the grid (implemented in TS) on the takes an infinite range and makes it finite
- [ ] Rust formula support using that function

**Comment by luke-quadratic** [comment]
advanced spreadsheet usage for audience that are unlikely to be users of Quadratic - plz reopen if you want to reexplore and make a higher prio
