### ISSUE TITLE
feat: cell linking / deep linking

### ISSUE THREAD

**Issue by waveminded** [quadratichq/quadratic#516]
The ability to create a **clickable link** to navigate directly to a targeted cell similar to an anchor tag in `HTML` 

Having an infinite canvas, data sets could be in many places all over the canvas. A quick link to navigate to a particular cell or section of the canvas would allow for quick navigation without having to remember the target cell.

 Idea/formula could be something like this:
`link("Click Me", A100)`

**Comment by davidkircos** [comment]
Not prioritised, let us know if you want this and what you'd use it for.
