### ISSUE TITLE
Windows - Command keys are not mapped correctly.

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#52]
- [x] Control C
- [x] Control V
- [x] Control + A
- [ ] Windows with mouse, not easy to pan and zoom.

**Comment by jimniels** [comment]
I think maybe this is probably old and has been fixed cc @HactarCE

**Comment by HactarCE** [comment]
Still very difficult to pan and zoom, unfortunately. Copy/paste are correctly mapped though

**Comment by davidkircos** [comment]
now we have a pan mode
