### ISSUE TITLE
Python Errors: Stack Trace is Wrong

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#53]
Line errors are not helpful when they come from other packages. Says a line number that isn’t in your code, without the full stack trace.

Example formula:
```python
import pandas as pd

a = pd.DataFrame()
a[0][0]

```

<img width="294" alt="Screen Shot 2022-04-20 at 3 08 44 PM" src="https://user-images.githubusercontent.com/3479421/164323348-655c4a0a-aa0d-4a0c-84f0-4c3aee5ca1e8.png">

**Comment by davidkircos** [comment]
Upgrading Pyodide and using the CodeRunner should help

https://pyodide.org/en/stable/usage/api/python-api/code.html#pyodide.code.CodeRunner

**Comment by ddimaria** [comment]
This is fixed in https://github.com/quadratichq/quadratic/tree/staging-2024-01
