### ISSUE TITLE
Ctrl+scroll doesn't zoom when cursor is over cell being edited

### ISSUE THREAD

**Issue by HactarCE** [quadratichq/quadratic#537]
To reproduce:
1. Double-click to edit a cell
2. Position the mouse cursor over the cell being edited
3. Scroll the mouse wheel to zoom in or out

Expected behavior: the sheet zooms as normal

Actual behavior: the sheet does not zoom

For comparison:
- Excel doesn't allow ctrl+scroll to zoom at all when editing a cell
- Sheets never allows ctrl+scroll to zoom, but when hovering over a cell I can trigger the browser's zoom (which is otherwise blocked)

**Comment by luke-quadratic** [comment]
#900 duplicate
