### ISSUE TITLE
feat: python cell highlights

### ISSUE THREAD

**Issue by juanbercoff** [quadratichq/quadratic#567]
![image](https://github.com/quadratichq/quadratic/assets/15874591/e7e1c691-88ca-40e3-8a1f-5b059f03fdfb)

I worked on it in 5af393b280c8a734312d50870daa7d774caf8dc3 
Ideally should be implemented in rust to avoid code duplication.

**Comment by AH-Hammi** [comment]
Would really love to see that, very good idea

**Comment by ddimaria** [comment]
This issue is resolved and in https://github.com/quadratichq/quadratic/tree/staging-2024-01
