### ISSUE TITLE
feat: add a 'trace dependents' feature (like excel)

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#579]
An in-app product request from a user to add something like excel's "trace dependents" so you can visualize what you're doing.

Example from Excel: two different cells reference `A1`

<img width="374" alt="CleanShot 2023-06-26 at 11 21 31@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/36cee80b-bb1c-4a1b-b172-3912ed02381c">

<img width="390" alt="CleanShot 2023-06-26 at 11 21 35@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/45670990-8ee2-4f17-9221-7b5536fca1c4">

And you can go to `A1` and hit "Trace dependents" and see:

<img width="383" alt="CleanShot 2023-06-26 at 11 21 44@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/4021f669-f6da-4030-92a2-be7c7e8ad639">

**Comment by davidkircos** [comment]
Not a priority, closing. Let us know if you want this!
