### ISSUE TITLE
feat: cmd + click to select multiple, unconnected cells

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#582]
As with Sheets and Excel, support CMD + CLICK to select multiple cells that are not sequential in a row or column.

![cmd-click-select](https://github.com/quadratichq/quadratic/assets/1316441/db773d57-924e-410c-bebd-f0f8600ce5aa)

**Comment by davidkircos** [comment]
Not sure of the use case for this. If anyone has one, feel free to reopen.

**Comment by jimniels** [comment]
I'm re-opening. I try to do this all the time, where I want to select multiple cells on a sheet that aren't directly in sequence.

For example: I want to grab these two cells and paint them both the same color at the same time.

![CleanShot 2024-01-26 at 22 49 11@2x](https://github.com/quadratichq/quadratic/assets/1316441/420a858a-2771-4a8f-b0b9-b65682a6518c)

Why can't I just click in one, then cmd+click the other, the formatting bar shows up (on the last one I clicked on) and I change the color.

I expect to use this command because it's an OS-level feature (and apps like Figma have it for multi-selection).

**Comment by davidfig** [comment]
Once we implement this, we should add this functionality to the formula inline editor, so you can insert multiple cells using the cmd/ctrl key.

**Comment by davidfig** [comment]
FYI: This will require a major rework of all the quadratic-core functions so they accept a list of SheetRects instead of a single one. Sigh.
