### ISSUE TITLE
Cant pan on a normal computer

### ISSUE THREAD

**Issue by MergenStudios** [quadratichq/quadratic#589]
I am trying to use quadratic on a normal computer with a normal mouse, but it is impossible to pan across the spreadsheet. 
The docs say:
"On supported mouse, drag with one finger"
But that doesnt specify any further, and I was unable to find what is meant by that.

**Comment by davidkircos** [comment]
Hey @MergenStudios you can scroll up and down with the scroll wheel. And Shift + Scroll will scroll side to side. 

Let me know if that works for you!

**Comment by MergenStudios** [comment]
Ah okay, that makes sense now. 
I'll close this issue now, but it might be usefull to clearly state that in the docs.
Thank you!

**Comment by davidkircos** [comment]
Thanks. I’ve updated the docs too!
