### ISSUE TITLE
fix: automatically set "$10" to currency

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#590]
[Per David's comment](https://github.com/quadratichq/quadratic/issues/590#issuecomment-1618909880)

> Yeah, I think the desired behavior is when entering "$10" to strip the value to 10 and set the formatting to right aligned currency

Like excel does it:

![Jul-03-2023 11-21-28](https://github.com/quadratichq/quadratic/assets/1316441/0f457ade-0fb6-46e0-a8fe-47f5a5a119d9)

---

**Old description** (see thread below)

When you have a column formatted as currency and change the decimal formatting, it changes any amounts already with cents, but not for whole dollar amounts

![Jul-03-2023 11-07-29](https://github.com/quadratichq/quadratic/assets/1316441/c1f55b51-53fa-4ed2-8bcb-429d30529b85)

**Comment by davidkircos** [comment]
I bet you typed "$10" and "$14" into those cells, which we do not automatically convert to a number.

It does work if you just type "10" and format as currency to "$10.00"

**Comment by davidkircos** [comment]
If that's the case, do we have that captured in an issue? Because we should fix it! 

$10 should automatically set the formatting to currency and replace the value with "10", stripping the $ from the value of the cell

**Comment by jimniels** [comment]
Ah ok yeah that makes sense.

I actually explicitly set the formatting on those cells to be "Currency" and it still didn't work — but now that makes sense, because they were entered as "$10". But even so, I would expect explicitly setting as currency to figure that out.

![Jul-03-2023 11-16-06](https://github.com/quadratichq/quadratic/assets/1316441/c81c65cd-ba65-45ad-b79f-12374fe35627)

**Comment by davidkircos** [comment]
Yeah, I think the desired behavior is when entering "$10" to strip the value to 10 and set the formatting to right aligned currency

**Comment by jimniels** [comment]
Agree, I'll update the description of this ticket.

**Comment by davidkircos** [comment]
Fixed in #609
