### ISSUE TITLE
bug: "save and run" unsaved changes doesn't work when python is still loading

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#610]
If Python is taking a long time to load, it's possible you can get into the editor and make some edits. If python still hasn't loaded and you go to close the editor, you'll get the popup that says "do you want to save your changes?" If you click "Save & Run" it won't actually save and run because python hasn't loaded yet.

<img width="1029" alt="CleanShot 2023-07-17 at 13 55 17@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/f7869c15-3bb2-4446-9b76-b83e5f8aec43">

From my testing, it seems like it closes the editor and just doesn't save whatever changes you had in there (but you don't know this until you re-open the editor for that cell).

I'm not sure what the best way is to solve this (and it seems like a pretty big edge case?). Seems like the options would be:

1. Don't trigger that "What do you want to do with your unsaved changes?" modal when python is still loading (and people will just lose their changes), or
2. Just hide the controls to save/close the editor entirely when python is loading, e.g.

 
<img width="571" alt="CleanShot 2023-07-17 at 13 59 01@2x" src="https://github.com/quadratichq/quadratic/assets/1316441/b17bb53b-bedd-4e7e-a042-3c41b24ef24b">

Or, 3) figure out a way to save changes to code that is separate from running code (but that seems like a big change i would guess...?)

Anyhow, it's a pretty big edge case I think, but the functionality there is technically incorrect in the current code, where it asks if you want to save your changes and if you say "yes" it won't because python hasn't loaded.

**Comment by luke-quadratic** [comment]
struggling to recreate with the substantial performance upgrades, can we close?

**Comment by luke-quadratic** [comment]
feel free to reopen if still issue, can't recreate
