### ISSUE TITLE
feat: AI for more than code generation

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#623]
We could set up a switch in the AI set to do various tasks. The AI can also determine, based on the input, what mode is most appropriate based on the request.

Example based on Replit's AI

<img width="352" alt="CleanShot 2023-07-26 at 09 22 31@2x" src="https://github.com/quadratichq/quadratic/assets/3479421/3ab1d727-af53-44a8-b5d6-6a8ecd817cc2">

<img width="639" alt="CleanShot 2023-07-26 at 09 22 20@2x" src="https://github.com/quadratichq/quadratic/assets/3479421/8571791e-6e16-45f2-8faa-443fd8ed68ee">

**Comment by luke-quadratic** [comment]
not currently a prio so closing, revisit in future 

these features have become rapidly adopted in all data tools so we'll have plenty of references if/when we want to tackle this
