### ISSUE TITLE
Feature Request: Application Specific right-click context menu

### ISSUE THREAD

**Issue by joshshapirotonal** [quadratichq/quadratic#64]
The current spreadsheet does not support right click context menu options specific to the application. It'd be great to have the standard spreadsheet options available through the context menu.

Current menu:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/100238227/171288578-e9f0a28b-d1ab-4da7-bfdb-2bc7d62f1075.png">

Standard spreadsheet context menu:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/100238227/171288615-b7e4da10-a3dc-4bb3-9fbf-16b79d24d09a.png">

**Comment by davidkircos** [comment]
<img width="667" alt="Screen Shot 2022-06-04 at 12 23 15 PM" src="https://user-images.githubusercontent.com/3479421/172016008-5620cf84-55af-403c-bb87-0ceab5293ee6.png">

@joshshapirotonal I created a simple right-click menu. We will add to it over time. PR #67
