### ISSUE TITLE
Interaction Improvements

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#654]
Quality of life improvements 

- [x] Moving cursor while in cell unfocuses cell 
- [ ] merge to cursor when using the keyboard
- [ ] When entering / leaving presentation mode, offset by the header so the content doesn't shift
- [x] Clicking column header to select all data doesn't work on cell output data
- [x] Arrow keys and focus while editing a cell.
- [x] Enter to focus cell + '=' opens cell type menu
- [x] Headers double-click when moving the mouse.
- [x] Hold down middle/scrollwheel mouse button to PAN
- [x] When in hand mode double clicking header seperator auto sets header size
- [x] Setting for font size of headings
- [x] Remove AI cell support (David K) [Note: maybe we should do this after we launch next. It will require a file migration and could be easier] on branch `remove-ai-cell-type`

**Comment by luke-quadratic** [comment]
revisit after Next
