### ISSUE TITLE
feat: Formula output should be linked to formula

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#66]
When selecting the output of a Formula or Python, it should should you the formula that creates it. Or allow you to override starting with a blank cell.
![CleanShot 2023-10-24 at 13 33 00@2x](https://github.com/quadratichq/quadratic/assets/3479421/deaa41f3-46ab-4cc7-a1b6-3b487fc88a78)

**Comment by luke-quadratic** [comment]
duplicate #926
