### ISSUE TITLE
fix: back button on auth actions

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#676]
Consider looking more closely at how the back button in the browser works when you log in and log out

e.g. If the user is logging in and the route goes `/path` -> `/login` -> `auth0.com` -> `/path`, we'd probably want the history stack to be...what? (same for logging out)

**Comment by davidkircos** [comment]
@jimniels is this still an issue? I think we did some work that improved this.

**Comment by jimniels** [comment]
It's improved. Let's close this for now
