### ISSUE TITLE
import dialog is slow to close when Canceling

### ISSUE THREAD

**Issue by robertlugg** [quadratichq/quadratic#679]
# Steps to reproduce the issue
Click on the 'Import' button on the top right.  Hit <Cancel> in the dialog that appears.  Immediately click on that same Import button on the top right of the main app window.  It will be inaccessible for 3 seconds or so
# Additional details / screenshots
This is the very first time I started up the app.
Edge offered to install as an app and I did.
Ideally you could get rid of the delay.  But if not provide some visual (such as greying the Import button) until the interface is available.

**Comment by davidkircos** [comment]
Hey,

The import button uses the System dialogue for selecting files, so we don't always have control over it's behavior.

What version of Edge are you using? We will look into it.

Thanks for the feedback!

**Comment by robertlugg** [comment]
using:
Version 116.0.1938.62 (Official build) (64-bit)

I see that my description of the problem wasn't clear.  The dialog goes away quick.  However, the main GUI is still frozen for a bit after that.

**Comment by davidkircos** [comment]
we do not officially support Microsoft Edge
