### ISSUE TITLE
feat: User defined categorical table of contents based on selected regions

### ISSUE THREAD

**Issue by j-c-cook** [quadratichq/quadratic#689]
If there are multiple phases of analysis on a single infinite sheet it may be nice to be able to create a _table of contents_ like structure by highlighting certain regions of the spreadsheet and defining a name (category). This could be useful to quickly switch back and forth between ideas that have been worked on.

**Comment by davidkircos** [comment]
Hey,

How do you picture a table of contents working?

**Comment by j-c-cook** [comment]
User highlight a cell. User click "Create shortcut". Quadratic provides a popup menu or a location on the side for the user to give it a name. Quadratic stores the name (and other defined names) in a location that's easily retrievable. When the user clicks on name shortcut, quadratic would move the screen to that cell and the cell would be highlighted. 

The single cell shortcut highlight feature would be its most basic form. An enhancement from that would be to allow for the desired area to be shown to be highlighted. That way when the short cut is clicked, the screen would both move to the location and scale (zoom in or out) based on the amount of selected area.

**Comment by davidkircos** [comment]
Interesting idea. We are thinking about adding named cells / named ranges. We could also make an index of these names and shortcuts to navigate to them.

So if you had a cell as `annual_revenue` it would show up in a list of named cells. And you could navigate to it.

**Comment by j-c-cook** [comment]
Thank you. 

The concept you describe may be used a lot. Performing operations with `np.array(annual_revenue)` may be simpler than remembering a cell range or re-highlighting. The feature could be used so often that automatically placing each _named cell range_ in a "table of contents" may result in eye garble over crowding.

Perhaps `project_a_expense` , `project_b_expense` and `project_c_expense` could be grouped into one shortcut item named `Expenses`  and when the shortcut is clicked each individual cell range will be moved in view. Possibly highlighted in a light gray to really provide visual feedback.

**Comment by davidkircos** [comment]
named ranges is on our roadmap
