### ISSUE TITLE
Offline-capable desktop app

### ISSUE THREAD

**Issue by du82** [quadratichq/quadratic#710]
It would be awesome to have an offline-capable desktop app that doesn't require a cloud backend or account so that I don't have to rely on a webapp that may go away in the future if Quadratic doesn't succeed.

Cloud / SaaS products go away all the time, so having a way to run Quadratic offline / without the cloud stuff would be awesome.

I'd also like to be able to create, import, export, and use the .grid file format as I would on the desktop app.

**Comment by du82** [comment]
I'd also like to be able to run Quadratic on airgapped machines without needing to set up a webserver and build it from scratch. An ideal desktop app would be like Excel (with the amazing Quadratic UI of course) where it's offline first but can sync to an account if you choose to log in with one.

**Comment by davidkircos** [comment]
Hey @du82 we plan on supporting offline file editing, but we do not have plans to allow Quadratic to be used without an account at the moment.

**Comment by du82** [comment]
> Hey @du82 we plan on supporting offline file editing, but we do not have plans to allow Quadratic to be used without an account at the moment.

why not? I dont want to be locked into a SaaS platform
