### ISSUE TITLE
feat: ability to have a cell be a clickable link

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#758]
Idk how we'd want to do this from a data perspective — like a cell could be a string with an optional type of "link" — but from a user's perspective it'd be great if text formatted as URLs became interactive and you could click on them.

### VSCode as an example

VSCode is a good example of implementation, I think, because the ability for something to be clicked as a link is _secondary_. It does not take over the primary function of the app, which is editing text.

For example, if you come across a URL in code, it is underlined to indicate it's a link and it can be interacted with:

![CleanShot 2023-10-30 at 11 43 30@2x](https://github.com/quadratichq/quadratic/assets/1316441/bb5fcdc2-137a-46d0-aef5-067a7a386c9b)

But clicking on it does the same thing that clicking on any other text does: it positions the cursor. Just because it's a link doesn't mean it overrides the default functionality of clicking in text files.

However, if you hover the text you get a little hint telling you how to interact with it.

![CleanShot 2023-10-30 at 11 43 35@2x](https://github.com/quadratichq/quadratic/assets/1316441/02488559-a4b4-476a-80d2-813d561604a6)

Then you learn to click on links in VSCode you hit CMD + click and anything that's underlined as a URL can be opened in a browser.

### In Quadratic

Something similar in quadratic would be nice. Maybe a good place to start would be we detect if something's a link rather than giving the ability to users to define cells as links. That might come later?

As an example, [I created this sheet](https://app.quadratichq.com/file/348ffe6d-4e95-434b-b850-392ab121b5af) where you can input a web page's address and it'll parse out all the URLs on that page and enumerate them.

![CleanShot 2023-10-30 at 11 41 55@2x](https://github.com/quadratichq/quadratic/assets/1316441/d9796ae9-d341-489d-a94f-843f7180b381)

It would be nice if I could click on any of those and open them in a browser.

**Comment by luke-quadratic** [comment]
common behavior in spreadsheets is auto-link and then single click to open link and click and hold to select cell (or just navigate to cell with arrow keys without opening link obviously)

and then right click to edit, add, remove links (linking becomes permanent option in right-click menu in this case) 

can also get fun with it and link to other workbooks or other sheets inside specific workbooks via these links as well which is nice, makes navigating in Quadratic a lot more seamless; e.g. link in the spirit of #732

**Comment by davidfig** [comment]
This turns out to be non-trivial. I have some ideas to implement it, but I'd love to integrate this with the inline formatting for text (eg, making part of the text bold). Links should be another aspect of that.
