### ISSUE TITLE
Empty formula error could be better

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#792]
![CleanShot 2023-11-13 at 19 12 19@2x](https://github.com/quadratichq/quadratic/assets/3479421/bce69b0e-d0d4-41f7-8249-aed1a624a7c7)

**Comment by davidkircos** [comment]
Should not allow saving and running of an empty cell, just keep it blank.

**Comment by luke-quadratic** [comment]
Error seems fine - write an actual formula
