### ISSUE TITLE
Deleting/undo delete of a sheet should rerun code cells 

### ISSUE THREAD

**Issue by davidfig** [quadratichq/quadratic#804]
Deleting/undo sheets does not rerun - this has various implications including code cell outlines aren't reapplied. Solution: rerun dependencies on undo.

**Comment by luke-quadratic** [comment]
To further illustrate - code outlines won't even appear for these since they're not reran 
![CleanShot 2024-07-23 at 13 36 25](https://github.com/user-attachments/assets/a167f54f-aeea-4e58-bd15-ce87bc793bd8)
