### ISSUE TITLE
feat: Support importing of Excel files

### ISSUE THREAD

**Issue by ddimaria** [quadratichq/quadratic#814]
Users seemed to be trying to upload XLSX files into Quadratic.  A simple current step is to covert to CSV and import.  The feature has several phases for incremental support.

- [ ] Support uploading of a XLSX file and treat it like a CSV import.  This is quite simple using existing [Rust libraries](https://github.com/tafia/calamine/blob/c66195c76676b29bdd78c6e977b3333082dc6fd5/examples/excel_to_csv.rs#L8).
- [ ] Parse formulas.  Matching Excel formulas to Quadratic formulas, convert to code cells on import.

**Comment by luke-quadratic** [comment]
Closed, not currently a priority use #871 for now.
