### ISSUE TITLE
Python client for uploading data

### ISSUE THREAD

**Issue by nikita-galileo** [quadratichq/quadratic#82]
Hi there! First of all love your product and the direction it's going. I come from a background of using numpy, pandas, vaex etc on a daily basis and so have learned to be pretty comfortable querying and manipulating data in python. Doing the same operations through google sheets, by comparison, makes me surprisingly frustrated.

I run a lot of ML experiments that output numbers it would be easiest for me to see in a spreadsheet format. Recently I looked into using the google sheets API or python clients (pygsheets and gsheets) and while the onboarding experience was quite terrible (it took so long to figure out authentication) the eventual experience has been quite nice for me. To keep it simple, I generate a pandas dataframe and push it up to a new worksheet I create for that experiment. 

That get's me now 80% of the way there because I then just have to apply some styling and copy some additional cells from a template I have and I get a mostly programmatically auto-generated output from my freeform experiments, which I love!

So, is there any ideas of in the future making a python client that makes it very easy to use quadratic as the frontend for ML experiment results or any other data science workflow? A lot of folks use jupyter notebook variants or streamlit, but they don't quite work as well as I think this could.

**Comment by davidkircos** [comment]
Hello @nikita-galileo 

We currently do not have plans to make a Python client for inserting data. However, you can use hit APIs directly from Quadratic to pull in data today. [Making requests.](https://docs.quadratic.to/reference/python-cell-reference/making-requests). Do you think that this could work for your use case? You also potentially could do your ML experiments entirely inside Quadratic.

Your frustration with the lack of programmability support with Google Sheets is exactly our motivation for building Quadratic. Your use case is interesting. If you'd like I'd be happy to have a chat about it. I'd love to learn from you.

**Comment by nikita-galileo** [comment]
I've been giving this a decent amount of thought! The "pull" model i.e. making requests from within quadratic to fetch data definitely makes a lot of sense. I wonder if there might be more use cases than what I encountered for this "push" model though too... I guess in some ways that would end up turning it into a lightweight quasi-database.

**Comment by davidkircos** [comment]
Yeah, I think it will make sense for us to support a "push" model via API once we have launched Quadratic Cloud. Similar to google sheets, but easier to authenticate with!

**Comment by luke-quadratic** [comment]
designing via #906
