### ISSUE TITLE
Is this open source?

### ISSUE THREAD

**Issue by Jak2k** [quadratichq/quadratic#824]

**Comment by luke-quadratic** [comment]
Quadratic's source code is available publicly in this repo. However, we do not provide any license to use, modify, or distribute our code.

**Comment by Jak2k** [comment]
So nobody can contribute?

**Comment by yaronhb** [comment]
@luke-quadratic I really really love the idea of a spreadsheet platform that you can adapt for various purposes.
I can think of dozens of specific [non-profit] use cases for it that depended on the ability to use the code and modify it, besides replacing the dreadful MS Excel format.
 
It could really be a new de facto spreadsheet standard that succeeds MS Excel. However, I believe this can only be achieved by incorporating copyleft techniques to the format and no less importantly to the editor. 

But the license is view only; meaning no one can use this project for any reason or purpose.
This raises the question, why is this project open-sourced? 

Will there be an option to use / modify the code for free in the future?

I'm not trying to be critical or in any way be entitled.
I'm genuinely interested in this project and its success.
