### ISSUE TITLE
bug: Formatting not preserved

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#859]
Formatting is getting reset on outputs in sheets 

To recreate - create new file --> put number in a cell --> reference that number in a different cell with Python --> format that new cell as currency or anything else --> reload file --> will have reset to non-currency 

![image](https://github.com/quadratichq/quadratic/assets/146771258/61354ca5-9893-4a3b-93df-a15b792347d4)

**Comment by ddimaria** [comment]
This bug was related to file importing in v1.4 and isolated to formatting of `Single` code cell outputs.
