### ISSUE TITLE
feat: autocomplete for formulas

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#860]
Really basic autocomplete that you would expect from a traditional spreadsheet is missing.

For example: if you have two columns and you want to create a third column that sums them, dragging down `C1` with the formula `SUM(A1:B1)`

![CleanShot 2023-11-21 at 11 11 19](https://github.com/quadratichq/quadratic/assets/1316441/064b410f-bd2d-48b4-927d-c7f009f73766)

Will just copy values and not actually formulas.

**Comment by luke-quadratic** [comment]
This should be tackled alongside this: https://github.com/quadratichq/quadratic/issues/1108

**Comment by luke-quadratic** [comment]
Solved in #1108
