### ISSUE TITLE
'=' to open pallete doesn't work if not first thing in cell 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#870]
'=' to open palette doesn't work if not first thing entered in cell 

![Peek 2023-11-22 16-25](https://github.com/quadratichq/quadratic/assets/146771258/42bd4bef-e59a-4588-b535-fccce42bbadf)

**Comment by davidkircos** [comment]
I can't replicate this. If the cell only contains `=`, it opens the code cell. Even if you type something first but then backspace and type `=`
