### ISSUE TITLE
bug: formula calculation and bottom bar digit precision

### ISSUE THREAD

**Issue by jimniels** [quadratichq/quadratic#881]
In #861 I intended to normalize the precision of the digits in the bottom bar

But I didn't test it thoroughly and now we get unnecessary digits of precision for 0 values

![CleanShot 2023-11-24 at 22 28 29@2x](https://github.com/quadratichq/quadratic/assets/1316441/3705224e-b198-4aa3-96e7-ff5cc41f5fbc)

At first, I was just going to wrap all of that in a `parseFloat()` so as to strip off the extra 0's when they are present, but then I started realizing some strange functional differences between `SUM` in formulas and what you get in the bottom bar in terms of precision

![CleanShot 2023-11-24 at 22 35 30@2x](https://github.com/quadratichq/quadratic/assets/1316441/de84f2b6-179c-458f-999f-9b8b2b8c1c11)

It seems like there are two things going on here:

1. Level of precision between the bottom bar and formulas doesn't match (should it? or should the grid have higher precision while the bottom bar always maxes out at 9 digits of precision like excel does)
2. Formula `SUM` is doing something weird and getting tons of digits of precision where it shouldn't

**Comment by luke-quadratic** [comment]
#877 suggests defaulting to 9 in the sheet. Intuition (and other sheets) says in the bottom bar should be <= in digits to what the sheet displays (e.g. libre seems to do 13 in the sheet, 10 in the bottom bar and it's a nice balance). Biased towards sig less precision.

**Comment by jimniels** [comment]
This will be fixed with #877
