### ISSUE TITLE
Shift+enter should move up

### ISSUE THREAD

**Issue by HactarCE** [quadratichq/quadratic#883]
1. Select a cell
2. Press shift+enter once to edit the cell
3. Press shift+enter again

Expected behavior (e.g., Google Sheets): on step 3, the cursor moves up by one cell

Actual behavior: on step 3, the cursor moves down by one cell

**Comment by HactarCE** [comment]
I can try to tackle this -- it seems like a good way to dip my toes into Typescript

**Comment by lchauha** [comment]
Hi @HactarCE I would like to work on this issue. Please assign this to me.
