### ISSUE TITLE
bug: Select all bounds is often incorrect

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#887]
![CleanShot 2023-11-27 at 15 15 25@2x](https://github.com/quadratichq/quadratic/assets/3479421/5b0eb7c5-3fd2-44a7-a1e8-546ff1ff535d)

**Comment by ddimaria** [comment]
I was unable to duplicate this from a new file. Using @davidkircos's file above, I was able to reproduce. That file had spills in it, so the bounds calculation is correct.  This is an old file that has been around through versions.  The current theory is that the file is corrupt.  I think we should close this issue @luke-quadratic

**Comment by davidkircos** [comment]
Seems like it was an old broken file. Closing for now.
