### ISSUE TITLE
bug: Close Editor with ESP bypasses saveCheck dialogue

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#907]
Behavior A:
- Make some changes in a cell's code
- Press ESC
- Code editor closes immediately without asking to save

Expected
- When pressing ESC it will still ask to save first

Edit, similar behavior
Behavior B:
- Make some changes in a cell's code
- Click to open another editor cell
- Original code editor closes without asking to save or automatically saving 

Expected
- Original code editor would either automatically save or give a prompt to save

**Comment by luke-quadratic** [comment]
As part of this issue, same experience when in an editor and opening a different editor/Python code cell. Have lost coding progress at least a dozen times doing this.
