### ISSUE TITLE
Charts - Followup Issues

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#911]
Charts PR Followup Issues

- [x]  bug: when resizing a column that would move a chart. the chart doesn't move until the page is reloaded `high` #920 
- [x]  .show() support `high`
- [x]  Charts placeholder does not show up at all in thumbnails
- [ ]  default to no icon bar, just pointer hovers for charts { 'displaylogo': False, 'displayModeBar': False}
- [x]  heading is behind HTML -- may need another renderer just for column/row headings
- [ ]  snapping (removed in build since it was not exact)
- [ ]  matplotlib

Note: charts are huge - makes files with charts more unstable

**Comment by luke-quadratic** [comment]
Will be closed and can be reopened for further issues once Matplotlib is merged
