### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by ddimaria** [quadratichq/quadratic#918]
Tracking issue for multiplayer.

- [x] MVP1: Basic Websocket Server and Frontend Presence https://github.com/quadratichq/quadratic/pull/903
  - [x] TS types for messages
  - [x] TS should only send messages once during its update loop (currently set to 15 messages/second)
  - [x] basic mulitplayer cursor
  - [x] basic multiplayer selection 
  - [x] Basic shell of a websocket server
  - [x] Shared state
  - [x] EnterRoom endpoint + code
  - [x] MouseMove endpoint + code
  - [x] Integration tests
- [ ] MVP2: Wild West https://github.com/quadratichq/quadratic/pull/912
  - [x] Transaction sharing
  - [x] Heartbeats
  - [x] Handle Disconnects
  - [x] Avatars
  - [x] Add Sheet Operation is broken 
  - [x] show when users are editing a cell
  - [x] follow other user's viewport
  - [ ] Authentication
  - [ ] multiplayer cursor shouldn't show when hovering over UI elements
  - [ ] auto generate TS types using [ts-rs](https://github.com/Aleph-Alpha/ts-rs)
  - [ ] Mock the socket in tests 
  - [ ] move heartbeat checks to the user level instead of rooms and close sockets on failure
  - [ ] spill error not propagating during MP
  - [ ] When the document / window loses focus hide that users cursor
  - [ ]  change all actions into Operations
  - [ ]  allow current async transaction to be saved in progress to apply incoming MP transactions (or, perhaps, allow operations to be applied w/o changing any GridController transaction data)
  - [ ]  (Possibly v next work) revert transactions based on transaction ordering

**Comment by luke-quadratic** [comment]
@ddimaria presuming this issue is ready to be closed with recent mp merge?
