### ISSUE TITLE
Ability to edit data in the sheet that is an output from code 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#945]
This issue is on feedback from a user (also something I've run into and wanted to be able to do). 

When you output data to the sheet from code and try to edit that data the sheet's response is a spill. This makes sense as you're trying to put data over what the code is trying to output to. Though often you want to edit that data a bit as part of your cleaning process. I suppose a potentially annoying thing here is if something else referencing your cleaned data but your code is executed again you're just writing over your cleaned data with the unclean data. 

Marking as open question cause not rly sure on this one.

**Comment by davidkircos** [comment]
My recommendation today is that if you are returning data from a code cell that needs cleaning, copy the output of the code cell and edit it off to one side.

We could allow "overrides" and ask when rerunning the code cell if you want to write over the "overrides". However, this seems overly complex, confusing, and potentially error-prone.

**Comment by luke-quadratic** [comment]
Sg, agreed, closing.
