### ISSUE TITLE
Fail CI with Typescript or ESLint Errors/Warnings

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#95]

**Comment by GermaVinsmoke** [comment]
Hey, @davidkircos I believe for ESLint errors and warnings, the project needs to have the style guide and ESLint setup.

And maybe it'll be better to have **"Typescript compile errors/warnings"**, **"Prettier"** and **"ESLint"** checks at the time of committing with the help of Husky.

**Comment by davidkircos** [comment]
already in place
