### ISSUE TITLE
Ability to toggle a linter on/off in the code editor(s) 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#953]
Common gripe I have with writing code in a notebook is collaboration with others inevitably ends up in inconsistent formatting and bad code practices overall, inevitably same issue with writing code in a spreadsheet. 

**Solution:** a simple toggle for having the linter run, perhaps another tab next to console for outputs if easier than any kind of formatting. Something like Ruff which is written in Rust is cool (used by Pyodide, FastAPI, SciPy, HuggingFace, etc).

**Comment by jimniels** [comment]
Agree. Personally I think we should be opinionated about this and have automatic code formatting turned on by default for all cells — and then tucked away somewhere the preference to turn it off

**Comment by davidkircos** [comment]
I agree. It used to do this but we disabled it at some point.

**Comment by luke-quadratic** [comment]
Doesn't feel as relevant in AI and future branches

Will reopen if ever becomes higher prio
