### ISSUE TITLE
Separate Formatting for Different Media, Including Print

### ISSUE THREAD

**Issue by aus10d** [quadratichq/quadratic#956]
I'd like to suggest a feature.
I'd like to see the ability to create different formatting for different media types, like how CSS works.
Specifically I'd like the ability to set a different formatting "look" when printing vs. on screen. This includes the ability to hide cells/rows/columns/ranges, like CSS visibility or display:none.
That way your data-entry screen could be really compact with notes and error messages, but the printable version (one that gets distributed for business purposes) is super pretty and can have wider columns, themed colors and bolding, no error messages, no notes, etc.
Hope this makes sense. Thanks for this great product. Loving it so far.

**Comment by luke-quadratic** [comment]
Cool idea! Can see how for data teams that present to various stakeholders it could be a hinderance to present something that has your notes and extra analysis (though perhaps making a copy that is prettified is one possible albeit hindered solution).  

Would be an extension of the presentation mode with a bunch of editing that is saved just for when in presentation mode I reckon (exclude certain cells, create specific formatting, etc)? Have you tried the first version of presentation mode yet? 

![CleanShot 2023-12-30 at 11 54 28@2x](https://github.com/quadratichq/quadratic/assets/146771258/f82fa70d-6064-4554-899a-2434c8c8c138)

**Comment by luke-quadratic** [comment]
Closing temporarily but will 100% re-open in the future if/when we re-explore sharing sheets as dashboards or similar concepts for presenting in business environments
