### ISSUE TITLE
Prompt user to press '=' to get started

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#969]
Decent number of incoming users are unaware of the fact they should press '=' on a cell to get started with a code cell type. Long-term we've discussed the desire for a simple walkthrough/tutorial in the users' first file; short-term there's a big assumed uptick in users that get to their first code-run by highlighting/flashing simple animation of cell (0,0) and saying 'press = to get started' in slightly greyed out text.

**Comment by jimniels** [comment]
Idea: make every cell say "Press '=' to get started" (or some way to best succinctly say "press = to get started with code or formulas") and it just sticks around as the placeholder text for every cell _until_ the user actually clicks '='  and triggers the cell type selection menu.

once they do that, we store a flag that turns this feature off, e.g. once we know they've done it once (or twice) we turn it off and get it out of their face.

![CleanShot 2024-01-06 at 17 49 44@2x](https://github.com/quadratichq/quadratic/assets/1316441/55ee4eb0-c7a0-481a-bb7e-a87d25ca5a13)

**Comment by jimniels** [comment]
That seems easy enough to build and ship and see if it makes a difference without being overly cumbersome and annoying (or having to build some big walkthrough when you first enter the sheet)

**Comment by luke-quadratic** [comment]
Oh that's really great thinking. +1 to this approach. (Would stop doing it after the first time they press =)

**Comment by luke-quadratic** [comment]
Merged
