### ISSUE TITLE
Include Python Files with a Grid

### ISSUE THREAD

**Issue by davidkircos** [quadratichq/quadratic#97]
use `pyImport` from Pyodide to be able to load a set of files with a grid so they can be imported by name and used in cells

https://pyodide.org/en/stable/usage/loading-custom-python-code.html

Tasks

- [ ] UI to add Python files 
- [ ] Python files are packed into the `.grid`
- [ ] User can import files and use them in cells
- [ ] Python files can not access the grid directly.

**Comment by luke-quadratic** [comment]
stale, readd if/when relevant
