### ISSUE TITLE
.CSV import fails if there is a description row 

### ISSUE THREAD

**Issue by luke-quadratic** [quadratichq/quadratic#970]
It's not uncommon for .CSV format to have a row that is a description right after the sheet title. In this case the .CSV import is getting cut off. E.g. the following .CSV should show up as column names and data, instead it will just import as the column names and the description (date range in this case). 
![CleanShot 2024-01-08 at 13 25 00@2x](https://github.com/quadratichq/quadratic/assets/146771258/9d3a7e15-e911-4017-9871-4cc1cf53f342)

**Comment by ddimaria** [comment]
Without an import UI, I don't think we can properly handle this case.  If there was an import UI, we could ask for the row number to start importing from, which could address this issue.

**Comment by luke-quadratic** [comment]
Noted, popping down to low prio in that case since the return on time seems relatively low. @ddimaria

**Comment by davidkircos** [comment]
I think it should just import the description into a cell on the second line. Then the data starting the row before that. No need for a import UI

**Comment by luke-quadratic** [comment]
reopen if any users run into issues around edge case CSVs, original case appears fixed
